# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-30 18:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0002_auto_20170830_1817'),
        ('physionetworks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='collaborators',
            field=models.ManyToManyField(blank=True, related_name='project_collaborator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='physionetworks_project', to='catalog.Contact'),
        ),
        migrations.AddField(
            model_name='project',
            name='contributors',
            field=models.ManyToManyField(blank=True, related_name='physionetworks_project', to='catalog.Contributor'),
        ),
        migrations.AddField(
            model_name='project',
            name='databaseinfo',
            field=models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.ProjectDatabase'),
        ),
        migrations.AddField(
            model_name='project',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='physionetworks_project', to='catalog.File'),
        ),
        migrations.AddField(
            model_name='project',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='physionetworks_project', to='catalog.Keyword'),
        ),
        migrations.AddField(
            model_name='project',
            name='license',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='physionetworks_project', to='catalog.License'),
        ),
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='project_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='toolkitinfo',
            field=models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.ProjectToolkit'),
        ),
    ]
