# Generated by Django 4.1.7 on 2023-04-11 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import project.modelcomponents.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0056_alter_trainingtype_required_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.FloatField(default=1.0)),
                ('training_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                    related_name='courses', to='user.trainingtype')),
            ],
            options={
                'permissions': [('can_view_course_guidelines', 'Can view course guidelines')],
                'default_permissions': ('change',),
                'unique_together': {('training_type', 'version')},
            },
        ),
        migrations.CreateModel(
            name='CourseProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('IP', 'In Progress'), ('C', 'Completed')], default='IP',
                                            max_length=2)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'course')},
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField()),
                ('description', project.modelcomponents.fields.SafeHTMLField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules',
                                             to='training.course')),
            ],
            options={
                'unique_together': {('course', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', project.modelcomponents.fields.SafeHTMLField()),
                ('order', models.PositiveIntegerField()),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes',
                                             to='training.module')),
            ],
        ),
        migrations.CreateModel(
            name='QuizChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('is_correct', models.BooleanField(default=False, verbose_name='Correct Choice?')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices',
                                           to='training.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='ModuleProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('IP', 'In Progress'), ('C', 'Completed')], default='IP',
                                            max_length=2)),
                ('last_completed_order', models.PositiveIntegerField(default=0, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                      related_name='module_progresses', to='training.courseprogress')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.module')),
            ],
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', project.modelcomponents.fields.SafeHTMLField()),
                ('order', models.PositiveIntegerField()),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents',
                                             to='training.module')),
            ],
        ),
        migrations.CreateModel(
            name='CompletedQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('module_progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                      related_name='completed_quizzes', to='training.moduleprogress')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='CompletedContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                              to='training.contentblock')),
                ('module_progress',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='completed_contents', to='training.moduleprogress')),
            ],
        ),
    ]
