# Generated by Django 4.1.13 on 2024-02-17 04:19

from django.db import migrations, models
import project.modelcomponents.fields


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_course_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=project.modelcomponents.fields.SafeHTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='title',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='valid_duration',
            field=models.DurationField(null=True),
        ),
    ]
