# Generated by Django 4.1.13 on 2024-03-07 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0060_backfill_trainingtype_slugs'),
        ('training', '0004_course_description_course_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='trainings',
            field=models.ManyToManyField(to='user.training'),
        ),
    ]
