# Generated by Django 4.2.11 on 2024-08-20 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0005_course_trainings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="trainings",
        ),
        migrations.AlterUniqueTogether(
            name="completedcontent",
            unique_together={("module_progress", "content")},
        ),
        migrations.AlterUniqueTogether(
            name="completedquiz",
            unique_together={("module_progress", "quiz")},
        ),
        migrations.AlterUniqueTogether(
            name="moduleprogress",
            unique_together={("course_progress", "module")},
        ),
    ]
