# Generated by Django 2.2.10 on 2020-04-17 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0041_auto_20200317_0834'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DBLogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(max_length=10)),
                ('message', models.TextField()),
                ('asctime', models.CharField(max_length=50)),
                ('module', models.CharField(max_length=50)),
                ('msg', models.TextField()),
                ('core_project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dblogentry', to='project.CoreProject')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dblogentry', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
