# Generated by Django 4.2.26 on 2026-01-21 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FederatedProject",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_project_uuid",
                    models.UUIDField(
                        db_index=True,
                        help_text="UUID of the project from the source site",
                    ),
                ),
                ("slug", models.SlugField(help_text="Project slug on the source site")),
                (
                    "version",
                    models.CharField(help_text="Project version", max_length=15),
                ),
                ("title", models.CharField(help_text="Project title", max_length=200)),
                ("abstract", models.TextField(help_text="Project abstract")),
                (
                    "doi",
                    models.CharField(
                        blank=True,
                        help_text="Digital Object Identifier",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        help_text="URL to project page on source site", max_length=500
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        blank=True,
                        help_text='Resource type (e.g., "Database", "Software")',
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "access_policy",
                    models.CharField(
                        blank=True,
                        help_text='Access policy (e.g., "Open", "Restricted")',
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "publish_datetime",
                    models.DateTimeField(
                        help_text="When the project was published on source site"
                    ),
                ),
                (
                    "main_storage_size",
                    models.BigIntegerField(
                        default=0, help_text="Storage size in bytes"
                    ),
                ),
                (
                    "topics",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='List of topic tags (e.g., ["ehr", "critical care"])',
                        null=True,
                    ),
                ),
                (
                    "last_fetched",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Last time this project metadata was updated",
                    ),
                ),
            ],
            options={
                "verbose_name": "Federated Project",
                "verbose_name_plural": "Federated Projects",
                "ordering": ["-publish_datetime", "title"],
            },
        ),
        migrations.CreateModel(
            name="FederatedSite",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_identifier",
                    models.SlugField(
                        help_text='Unique identifier for this site (e.g., "physionet-mit")',
                        unique=True,
                    ),
                ),
                (
                    "site_name",
                    models.CharField(
                        help_text='Display name for this site (e.g., "PhysioNet")',
                        max_length=200,
                    ),
                ),
                (
                    "api_base_url",
                    models.URLField(
                        help_text="Base URL for the federation API", max_length=500
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether to sync data from this site"
                    ),
                ),
                (
                    "last_sync_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of last successful sync",
                        null=True,
                    ),
                ),
                (
                    "last_sync_status",
                    models.CharField(
                        choices=[
                            ("never", "Never synced"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("in_progress", "In progress"),
                        ],
                        default="never",
                        help_text="Status of most recent sync attempt",
                        max_length=20,
                    ),
                ),
                (
                    "api_key",
                    models.CharField(
                        blank=True,
                        help_text="API key for authentication (optional)",
                        max_length=200,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Federated Site",
                "verbose_name_plural": "Federated Sites",
                "ordering": ["site_name"],
            },
        ),
        migrations.CreateModel(
            name="FederationSyncLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(help_text="When sync started")),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="When sync completed", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("partial", "Partial success"),
                        ],
                        help_text="Overall status of this sync",
                        max_length=20,
                    ),
                ),
                (
                    "projects_fetched",
                    models.IntegerField(
                        default=0, help_text="Total projects fetched from API"
                    ),
                ),
                (
                    "projects_created",
                    models.IntegerField(
                        default=0, help_text="New projects added to cache"
                    ),
                ),
                (
                    "projects_updated",
                    models.IntegerField(
                        default=0, help_text="Existing projects updated"
                    ),
                ),
                (
                    "projects_deleted",
                    models.IntegerField(
                        default=0, help_text="Projects removed during full refresh"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if sync failed"
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        help_text="The site that was synced",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_logs",
                        to="search.federatedsite",
                    ),
                ),
            ],
            options={
                "verbose_name": "Federation Sync Log",
                "verbose_name_plural": "Federation Sync Logs",
                "ordering": ["-started_at"],
            },
        ),
        migrations.AddIndex(
            model_name="federatedsite",
            index=models.Index(
                fields=["is_active", "last_sync_datetime"],
                name="search_fede_is_acti_0bad89_idx",
            ),
        ),
        migrations.AddField(
            model_name="federatedproject",
            name="source_site",
            field=models.ForeignKey(
                help_text="The federated site this project belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cached_projects",
                to="search.federatedsite",
            ),
        ),
        migrations.AddIndex(
            model_name="federationsynclog",
            index=models.Index(
                fields=["site", "-started_at"], name="search_fede_site_id_a35c25_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="federationsynclog",
            index=models.Index(
                fields=["status", "-started_at"], name="search_fede_status_d61696_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="federatedproject",
            index=models.Index(
                fields=["public_project_uuid"], name="search_fede_public__7ccd7c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="federatedproject",
            index=models.Index(
                fields=["slug", "version"], name="search_fede_slug_e5662d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="federatedproject",
            index=models.Index(
                fields=["publish_datetime"], name="search_fede_publish_b25fc1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="federatedproject",
            index=models.Index(
                fields=["resource_type"], name="search_fede_resourc_ab7754_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="federatedproject",
            index=models.Index(fields=["title"], name="search_fede_title_bfd9cb_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="federatedproject",
            unique_together={("source_site", "public_project_uuid")},
        ),
    ]
