# Generated by Django 4.2.22 on 2025-10-16 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FederatedSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Unique identifier (e.g., 'healthdatanexus')", max_length=100, unique=True)),
                ('display_name', models.CharField(help_text="Display name shown in UI (e.g., 'Health Data Nexus')", max_length=200)),
                ('base_url', models.URLField(help_text="Base URL (e.g., 'https://healthdatanexus.ca')", max_length=500)),
                ('api_endpoint', models.CharField(default='/api/v1/projects/published/search/', help_text='API endpoint path for search', max_length=500)),
                ('site_type', models.CharField(choices=[('physionet', 'PhysioNet Instance'), ('generic_api', 'Generic API Repository')], default='physionet', help_text='Type of repository', max_length=20)),
                ('enabled', models.BooleanField(default=True, help_text='Enable/disable this site in federated search')),
                ('auth_token', models.CharField(blank=True, help_text='Optional API key/token for authenticated access', max_length=500, null=True)),
                ('timeout_seconds', models.PositiveIntegerField(default=5, help_text='Request timeout in seconds')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower = higher priority)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Federated Site',
                'verbose_name_plural': 'Federated Sites',
                'ordering': ['order', 'name'],
            },
        ),
    ]
