# Generated by Django 4.2.27 on 2026-03-16 23:28

from django.db import migrations
import project.fields


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='federatedproject',
            name='abstract',
            field=project.fields.SafeHTMLField(help_text='Project abstract'),
        ),
    ]
