# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-07 16:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reset_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('reset_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('email', models.EmailField(default='', max_length=255, verbose_name='email address')),
                ('action', models.CharField(default='', max_length=15)),
            ],
        ),
    ]
