# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-07 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, default='', null=True, upload_to='media/Users/photo/'),
        ),
    ]
