# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-10 20:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170407_1818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_action',
            old_name='reset_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='user_action',
            old_name='reset_date',
            new_name='date',
        ),
    ]
