# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-12 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170410_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, default='', null=True, upload_to=b''),
        ),
    ]
