# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-12 14:31
from __future__ import unicode_literals

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20170412_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, default='', null=True, upload_to=users.models.user_directory_path),
        ),
    ]
