# Generated by Django 2.2.24 on 2021-11-24 22:06

from django.db import migrations, models
import project.modelcomponents.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('ABOUT', 'about'), ('SHARE', 'share')], max_length=16)),
                ('title', models.CharField(max_length=64)),
                ('content', project.modelcomponents.fields.SafeHTMLField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ('order',),
                'unique_together': {('page', 'order')},
            },
        ),
    ]
