# Generated by Django 2.2.27 on 2022-02-28 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    def migrate_forward(apps, schema_editor):
        StaticPage = apps.get_model('physionet', 'StaticPage')
        Section = apps.get_model('physionet', 'Section')

        (about_page, _) = StaticPage.objects.get_or_create(
            url='/about/', title='About')

        (about_pub_page, _) = StaticPage.objects.get_or_create(
            url='/about/share', title='Share')

        for section in Section.objects.all():
            if section.page == 'Page.ABOUT':
                section.static_page = about_page
            if section.page == 'Page.SHARE':
                section.static_page = about_pub_page
            section.save()

    def migrate_backward(apps, schema_editor):
        pass

    dependencies = [
        ('physionet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('url', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='section',
            name='static_page',
            field=models.ForeignKey(null=True, default=None, on_delete=django.db.models.deletion.CASCADE,
                                    to='physionet.StaticPage'),
        ),
        migrations.RunPython(migrate_forward, migrate_backward),
        migrations.AlterField(
            model_name='section',
            name='page',
            field=models.CharField(null=True, blank=True),
        )
    ]
