# Generated by Django 2.2.26 on 2022-02-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physionet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='page',
            field=models.CharField(
                choices=[('ABOUT', 'about'), ('SHARE', 'share'), ('SSO_LOGIN', 'sso login')], max_length=16),
        ),
    ]
