# Generated by Django 2.2.27 on 2022-02-21 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('physionet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'default_permissions': ('change',), 'ordering': ('order',)},
        ),
    ]
