# Generated by Django 2.2.27 on 2022-03-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physionet', '0003_auto_20220228_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticpage',
            name='nav_bar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staticpage',
            name='nav_order',
            field=models.PositiveSmallIntegerField(blank=True, null=True, unique=True),
        ),
    ]
