# Generated by Django 2.2.27 on 2022-03-30 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('physionet', '0005_auto_20220221_0346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'default_permissions': (), 'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='staticpage',
            options={'default_permissions': ('change',)},
        ),
    ]
