# Generated by Django 3.1.14 on 2022-11-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physionet', '0006_auto_20220330_0404'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontPageButton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20, unique=True)),
                ('url', models.CharField(max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'ordering': ('order',),
                'default_permissions': ('change',),
            },
        ),
    ]
