# Generated by Django 3.1.14 on 2022-11-17 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physionet', '0006_auto_20220330_0404'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticpage',
            name='front_page',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
