# Generated by Django 4.1.13 on 2025-06-05 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("physionet", "0007_frontpagebutton"),
    ]

    operations = [
        migrations.AddField(
            model_name="frontpagebutton",
            name="associated_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="frontpagebuttons/"
            ),
        ),
    ]
