# Generated by Django 4.2.11 on 2024-05-15 20:22

from django.db import migrations, models
import django.db.models.deletion
import project.modelcomponents.fields


class Migration(migrations.Migration):

    dependencies = [
        ("physionet", "0007_frontpagebutton"),
    ]

    operations = [
        migrations.CreateModel(
            name="Process",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=64)),
                ("slug", models.CharField(max_length=64, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "default_permissions": (),
                "unique_together": {("title", "slug")},
            },
        ),
        migrations.CreateModel(
            name="Step",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=64)),
                ("slug", models.CharField(max_length=64)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "process",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="physionet.process",
                    ),
                ),
            ],
            options={
                "ordering": ("order",),
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="StepDetails",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=64)),
                ("content", project.modelcomponents.fields.SafeHTMLField(blank=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("slug", models.CharField(max_length=64)),
                ("tip", models.BooleanField(default=False)),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="physionet.step"
                    ),
                ),
            ],
            options={
                "ordering": ("order",),
                "default_permissions": (),
                "unique_together": {("step", "order")},
            },
        ),
    ]
