# Generated by Django 4.1.13 on 2024-02-23 13:00

from django.db import migrations, models
import django.db.models.deletion
import project.modelcomponents.fields


class Migration(migrations.Migration):

    dependencies = [
        ('physionet', '0007_frontpagebutton'),
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('process_name', models.CharField(max_length=64)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ('order',),
                'default_permissions': (),
            },
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'default_permissions': ()},
        ),
        migrations.CreateModel(
            name='StepDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('content', project.modelcomponents.fields.SafeHTMLField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('tip', models.BooleanField(default=False)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='physionet.step')),
            ],
            options={
                'default_permissions': (),
                'unique_together': {('step', 'order')},
            },
        ),
    ]
