# Generated by Django 4.2.15 on 2025-06-06 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physionet', '0007_frontpagebutton'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontpagebutton',
            name='associated_image_path',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='frontpagebutton',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
