# Generated by Django 4.2.11 on 2024-05-08 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("physionet", "0008_step_alter_section_options_stepdetails"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="section",
            options={"default_permissions": (), "ordering": ("order",)},
        ),
        migrations.AlterModelOptions(
            name="stepdetails",
            options={"default_permissions": (), "ordering": ("order",)},
        ),
    ]
