# Generated by Django 4.2.11 on 2024-05-08 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("physionet", "0009_alter_section_options_alter_stepdetails_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="step",
            name="process_name",
        ),
        migrations.CreateModel(
            name="Process",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=64)),
                ("slug", models.CharField(max_length=64, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "default_permissions": (),
                "unique_together": {("title", "slug")},
            },
        ),
        migrations.AddField(
            model_name="step",
            name="process",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="steps",
                to="physionet.process",
            ),
        ),
    ]
