# Generated by Django 2.1.4 on 2018-12-31 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeproject',
            name='editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editing_activeprojects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activeproject',
            name='license',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.License'),
        ),
        migrations.AlterField(
            model_name='archivedproject',
            name='editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editing_archivedprojects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='archivedproject',
            name='license',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.License'),
        ),
        migrations.AlterField(
            model_name='author',
            name='corresponding_email',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.AssociatedEmail'),
        ),
        migrations.AlterField(
            model_name='publishedproject',
            name='editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editing_publishedprojects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='publishedproject',
            name='license',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.License'),
        ),
        migrations.AlterField(
            model_name='publishedproject',
            name='newest_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='older_versions', to='project.PublishedProject'),
        ),
        migrations.AlterField(
            model_name='storagerequest',
            name='responder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
