# Generated by Django 2.1.7 on 2019-02-15 22:50

from django.db import migrations, models
import project.validators


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20190208_1210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publishedproject',
            old_name='special_storage_size',
            new_name='compressed_storage_size',
        ),
        migrations.RemoveField(
            model_name='publishedproject',
            name='total_storage_size',
        ),
        migrations.AlterField(
            model_name='publishedproject',
            name='doi',
            field=models.CharField(max_length=50, unique=True, validators=[project.validators.validate_doi]),
        ),
    ]
