# Generated by Django 2.1.7 on 2019-03-08 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20190306_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishedproject',
            name='doi',
            field=models.CharField(default='', max_length=50),
        ),
    ]
