# Generated by Django 2.1.7 on 2019-03-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20190308_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeproject',
            name='version',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='archivedproject',
            name='version',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='publishedproject',
            name='version',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
