# Generated by Django 2.1.7 on 2019-03-19 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20190314_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeproject',
            name='resource_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Database'), (1, 'Software'), (2, 'Challenge')]),
        ),
        migrations.AlterField(
            model_name='archivedproject',
            name='resource_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Database'), (1, 'Software'), (2, 'Challenge')]),
        ),
        migrations.AlterField(
            model_name='license',
            name='resource_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Database'), (1, 'Software'), (2, 'Challenge')]),
        ),
        migrations.AlterField(
            model_name='publishedproject',
            name='resource_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Database'), (1, 'Software'), (2, 'Challenge')]),
        ),
    ]
