# Generated by Django 2.1.7 on 2019-04-17 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0013_auto_20190412_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='GCP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket_name', models.CharField(max_length=100, null=True)),
                ('is_private', models.BooleanField(default=False)),
                ('sent_files', models.BooleanField(default=False)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('finished_datetime', models.DateTimeField(null=True)),
                ('managed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gcp_manager', to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gcp', to='project.PublishedProject')),
            ],
        ),
    ]
