# Generated by Django 2.1.7 on 2019-04-18 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_gcp'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishedproject',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
