# Generated by Django 2.1.7 on 2019-04-22 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_publishedproject_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='license',
            name='resource_type',
        ),
        migrations.AddField(
            model_name='license',
            name='resource_types',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
