# Generated by Django 2.1.7 on 2019-04-27 06:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('project', '0017_auto_20190425_1854'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='author',
            unique_together={('user', 'content_type', 'object_id'), ('display_order', 'content_type', 'object_id')},
        ),
        migrations.AlterUniqueTogether(
            name='publishedauthor',
            unique_together={('user', 'project'), ('display_order', 'project')},
        ),
    ]
