# Generated by Django 2.1.7 on 2019-04-30 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_auto_20190427_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishedproject',
            name='has_wfdb',
            field=models.BooleanField(default=False),
        ),
    ]
