# Generated by Django 2.1.7 on 2019-04-30 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0019_publishedproject_has_wfdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishedproject',
            name='deprecated_files',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activeproject',
            name='resource_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Database'), (1, 'Software'), (2, 'Challenge'), (3, 'Model')]),
        ),
        migrations.AlterField(
            model_name='archivedproject',
            name='resource_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Database'), (1, 'Software'), (2, 'Challenge'), (3, 'Model')]),
        ),
        migrations.AlterField(
            model_name='publishedproject',
            name='resource_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Database'), (1, 'Software'), (2, 'Challenge'), (3, 'Model')]),
        ),
    ]
