# Generated by Django 2.1.7 on 2019-05-02 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0020_auto_20190430_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='project.PublishedProject'),
        ),
    ]
