# Generated by Django 2.1.7 on 2019-05-15 20:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0021_auto_20190502_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='authorinvitation',
            name='creation_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='authorinvitation',
            name='invitation_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='authorinvitation',
            name='reply_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
