# Generated by Django 2.1.7 on 2019-05-10 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0021_auto_20190502_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='shared',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='publishedauthor',
            name='shared',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
