# Generated by Django 2.1.7 on 2019-05-29 19:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0022_author_creation_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiskQuota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quota', models.BigIntegerField(default=104857600, validators=[django.core.validators.MaxValueValidator(109951162777600), django.core.validators.MinValueValidator(104857600)])),
                ('last_update', models.DateTimeField(auto_now_add=True)),
                ('group', models.CharField(max_length=100, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.CoreProject')),
            ],
        ),
    ]
