# Generated by Django 2.1.7 on 2019-06-20 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0022_author_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeproject',
            name='short_description',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='archivedproject',
            name='short_description',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='publishedproject',
            name='short_description',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
