# Generated by Django 2.1.7 on 2019-06-25 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0023_auto_20190620_1845'),
        ('project', '0022_auto_20190510_1740'),
    ]

    operations = [
    ]
