# Generated by Django 2.1.9 on 2019-06-21 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0023_diskquota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diskquota',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
