# Generated by Django 2.1.9 on 2019-07-24 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0025_auto_20190723_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editlog',
            name='author_comments',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
