# Generated by Django 2.1.9 on 2019-07-25 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0026_auto_20190724_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeproject',
            name='author_comments',
            field=models.CharField(blank=True, default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='archivedproject',
            name='author_comments',
            field=models.CharField(blank=True, default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='copyeditlog',
            name='changelog_summary',
            field=models.CharField(blank=True, default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='gcp',
            name='bucket_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='publishedproject',
            name='author_comments',
            field=models.CharField(blank=True, default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='storagerequest',
            name='response_message',
            field=models.CharField(blank=True, default='', max_length=10000),
        ),
    ]
