# Generated by Django 2.1.9 on 2019-07-25 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0027_auto_20190725_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.PositiveSmallIntegerField(choices=[(0, 'local'), (1, 'aws-open-data'), (2, 'aws-s3'), (3, 'gcp-bucket'), (4, 'gcp-bigquery')])),
                ('location', models.CharField(max_length=100, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataaccesss', to='project.PublishedProject')),
            ],
        ),
        migrations.AddField(
            model_name='gcp',
            name='sent_zip',
            field=models.BooleanField(default=False),
        ),
    ]
