# Generated by Django 2.1.9 on 2019-08-16 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0025_auto_20190710_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=64)),
                ('passphrase', models.CharField(max_length=128)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('expiration_datetime', models.DateTimeField(null=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anonymous_access_creator', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('object_id', models.PositiveIntegerField())
            ],
        ),
        migrations.AlterUniqueTogether(
            name='anonymousaccess',
            unique_together={('content_type', 'object_id')},
        ),
    ]
