# Generated by Django 2.2.3 on 2019-10-17 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0031_anonymousaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeproject',
            name='latest_reminder',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='archivedproject',
            name='latest_reminder',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
