# Generated by Django 2.2.3 on 2019-10-09 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0031_anonymousaccess'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publishedproject',
            name='approved_users',
        ),
    ]
