# Generated by Django 2.2.4 on 2019-10-29 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0032_remove_publishedproject_approved_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeproject',
            name='latest_reminder',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='archivedproject',
            name='latest_reminder',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
