# Generated by Django 2.2.6 on 2019-11-14 18:01

from django.db import migrations, models
import project.validators


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0033_auto_20191029_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeproject',
            name='title',
            field=models.CharField(max_length=200, validators=[project.validators.validate_title]),
        ),
        migrations.AlterField(
            model_name='archivedproject',
            name='title',
            field=models.CharField(max_length=200, validators=[project.validators.validate_title]),
        ),
        migrations.AlterField(
            model_name='publishedproject',
            name='title',
            field=models.CharField(max_length=200, validators=[project.validators.validate_title]),
        ),
    ]
