# Generated by Django 2.2.10 on 2020-02-26 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0034_auto_20191114_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='gcp',
            name='access_group',
            field=models.CharField(max_length=170, null=True),
        ),
    ]
