# Generated by Django 2.2.6 on 2019-11-25 20:00

from django.db import migrations, models
import project.validators
import user.validators


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0034_auto_20191114_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliation',
            name='name',
            field=models.CharField(max_length=202, validators=[user.validators.validate_affiliation]),
        ),
        migrations.AlterField(
            model_name='publishedaffiliation',
            name='name',
            field=models.CharField(max_length=202, validators=[user.validators.validate_affiliation]),
        ),
        migrations.AlterField(
            model_name='publishedtopic',
            name='description',
            field=models.CharField(max_length=50, validators=[project.validators.validate_topic]),
        ),
        migrations.AlterField(
            model_name='topic',
            name='description',
            field=models.CharField(max_length=50, validators=[project.validators.validate_topic]),
        ),
    ]
