# Generated by Django 2.2.6 on 2019-12-02 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0035_add_project_sections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activeproject',
            name='acknowledgements',
        ),
        migrations.RemoveField(
            model_name='activeproject',
            name='background',
        ),
        migrations.RemoveField(
            model_name='activeproject',
            name='conflicts_of_interest',
        ),
        migrations.RemoveField(
            model_name='activeproject',
            name='content_description',
        ),
        migrations.RemoveField(
            model_name='activeproject',
            name='installation',
        ),
        migrations.RemoveField(
            model_name='activeproject',
            name='methods',
        ),
        migrations.RemoveField(
            model_name='activeproject',
            name='release_notes',
        ),
        migrations.RemoveField(
            model_name='activeproject',
            name='usage_notes',
        ),
        migrations.RemoveField(
            model_name='archivedproject',
            name='acknowledgements',
        ),
        migrations.RemoveField(
            model_name='archivedproject',
            name='background',
        ),
        migrations.RemoveField(
            model_name='archivedproject',
            name='conflicts_of_interest',
        ),
        migrations.RemoveField(
            model_name='archivedproject',
            name='content_description',
        ),
        migrations.RemoveField(
            model_name='archivedproject',
            name='installation',
        ),
        migrations.RemoveField(
            model_name='archivedproject',
            name='methods',
        ),
        migrations.RemoveField(
            model_name='archivedproject',
            name='release_notes',
        ),
        migrations.RemoveField(
            model_name='archivedproject',
            name='usage_notes',
        ),
        migrations.RemoveField(
            model_name='publishedproject',
            name='acknowledgements',
        ),
        migrations.RemoveField(
            model_name='publishedproject',
            name='background',
        ),
        migrations.RemoveField(
            model_name='publishedproject',
            name='conflicts_of_interest',
        ),
        migrations.RemoveField(
            model_name='publishedproject',
            name='content_description',
        ),
        migrations.RemoveField(
            model_name='publishedproject',
            name='installation',
        ),
        migrations.RemoveField(
            model_name='publishedproject',
            name='methods',
        ),
        migrations.RemoveField(
            model_name='publishedproject',
            name='release_notes',
        ),
        migrations.RemoveField(
            model_name='publishedproject',
            name='usage_notes',
        ),
    ]
