# Generated by Django 2.2.6 on 2020-02-07 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0035_auto_20191125_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeproject',
            name='doi',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='archivedproject',
            name='doi',
            field=models.CharField(default='', max_length=50),
        ),
    ]
