# Generated by Django 2.2.9 on 2020-02-19 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0035_auto_20191125_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeproject',
            name='is_self_managed_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='archivedproject',
            name='is_self_managed_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publishedproject',
            name='is_self_managed_access',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='DataAccessRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_datetime', models.DateTimeField(auto_now_add=True)),
                ('data_use_purpose', models.CharField(max_length=2000)),
                ('status', models.PositiveSmallIntegerField(choices=[('', 'Pending'), (1, 'Reject'), (2, 'Accept')], default=0)),
                ('decision_datetime', models.DateTimeField(null=True)),
                ('responder_comments', models.CharField(blank=True, max_length=500)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_access_request_project', to='project.PublishedProject')),
                ('responder', models.ForeignKey(null=True, on_delete=models.SET(1), related_name='data_access_request_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
