# Generated by Django 2.2.10 on 2020-02-26 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0035_auto_20191125_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='gcp',
            name='access_group',
            field=models.CharField(max_length=170, null=True),
        ),
    ]
