# Generated by Django 2.2.6 on 2020-02-11 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0036_auto_20200206_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='editlog',
            name='auto_doi',
            field=models.BooleanField(default=False),
        ),
    ]
