# Generated by Django 2.2.4 on 2020-02-21 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0036_auto_20200206_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeproject',
            name='doi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='archivedproject',
            name='doi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='coreproject',
            name='doi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='publishedproject',
            name='doi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
