# Generated by Django 2.2.6 on 2020-02-14 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0037_editlog_auto_doi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeproject',
            name='doi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='archivedproject',
            name='doi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='coreproject',
            name='doi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='publishedproject',
            name='doi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
