# Generated by Django 2.1.7 on 2019-05-10 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0039_auto_20200214_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='shared',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='publishedauthor',
            name='shared',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]