# Generated by Django 2.2.10 on 2020-03-05 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0039_auto_20200214_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='gcp',
            name='access_group',
            field=models.CharField(max_length=170, null=True),
        ),
    ]
