# Generated by Django 2.2.9 on 2020-03-17 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import project.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0040_gcp_access_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeproject',
            name='is_self_managed_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activeproject',
            name='self_managed_dua',
            field=project.models.SafeHTMLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='activeproject',
            name='self_managed_request_template',
            field=project.models.SafeHTMLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='archivedproject',
            name='is_self_managed_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='archivedproject',
            name='self_managed_dua',
            field=project.models.SafeHTMLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='archivedproject',
            name='self_managed_request_template',
            field=project.models.SafeHTMLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='publishedproject',
            name='is_self_managed_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publishedproject',
            name='self_managed_dua',
            field=project.models.SafeHTMLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='publishedproject',
            name='self_managed_request_template',
            field=project.models.SafeHTMLField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='DataAccessRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_datetime', models.DateTimeField(auto_now_add=True)),
                ('data_use_title', models.CharField(default='', max_length=200)),
                ('data_use_purpose', project.models.SafeHTMLField(max_length=10000)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Reject'), (3, 'Accept')], default=0)),
                ('decision_datetime', models.DateTimeField(null=True)),
                ('responder_comments', project.models.SafeHTMLField(blank=True, max_length=10000)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_access_requests', to='project.PublishedProject')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('responder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_access_request_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
