# Generated by Django 2.2.9 on 2020-04-07 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0041_auto_20200317_0834'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataAccessRequestReviewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitation_date', models.DateTimeField(auto_now_add=True)),
                ('is_revoked', models.BooleanField(default=False)),
                ('revocation_date', models.DateTimeField(null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_access_request_reviewers', to='project.PublishedProject')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
