# Generated by Django 2.2.10 on 2020-04-10 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    MIGRATE_AFTER_INSTALL = True

    dependencies = [
        ('project', '0042_incremental_storage_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishedproject',
            name='incremental_storage_size',
            field=models.BigIntegerField(default=0),
        ),
    ]
