# Generated by Django 2.2.10 on 2020-08-05 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0044_auto_20200512_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duasignature',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dua_signatures', to=settings.AUTH_USER_MODEL),
        ),
    ]
