# Generated by Django 2.2.13 on 2020-09-08 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0045_auto_20200805_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='affiliations',
            field=models.CharField(max_length=250),
        ),
    ]
