# Generated by Django 2.2.13 on 2021-05-04 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0045_auto_20200805_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeproject',
            name='author_comments',
            field=models.CharField(blank=True, default='', max_length=20000),
        ),
        migrations.AlterField(
            model_name='archivedproject',
            name='author_comments',
            field=models.CharField(blank=True, default='', max_length=20000),
        ),
        migrations.AlterField(
            model_name='editlog',
            name='author_comments',
            field=models.CharField(default='', max_length=20000),
        ),
        migrations.AlterField(
            model_name='editlog',
            name='editor_comments',
            field=models.CharField(max_length=20000),
        ),
        migrations.AlterField(
            model_name='publishedproject',
            name='author_comments',
            field=models.CharField(blank=True, default='', max_length=20000),
        ),
    ]
