# Generated by Django 2.2.24 on 2021-10-08 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0046_auto_20210504_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('ACCESS', 'Access'), ('GCP', 'GCP')], max_length=64, editable=False)),
                ('data', models.TextField(max_length=512)),
                ('count', models.PositiveIntegerField(default=1)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_access_datetime', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.PublishedProject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('project.log',),
        ),
        migrations.CreateModel(
            name='GCPLog',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('project.log',),
        ),
    ]
