# Generated by Django 2.2.24 on 2021-11-29 09:27

from django.db import migrations, models
from project.modelcomponents.access import AccessPolicy


def migrate_forward(apps, schema_editor):
    ActiveProject = apps.get_model('project', 'ActiveProject')
    ArchivedProject = apps.get_model('project', 'ArchivedProject')
    PublishedProject = apps.get_model('project', 'PublishedProject')

    ActiveProject.objects.filter(is_self_managed_access=True).update(access_policy=AccessPolicy.CONTRIBUTOR_REVIEW)
    ArchivedProject.objects.filter(is_self_managed_access=True).update(access_policy=AccessPolicy.CONTRIBUTOR_REVIEW)
    PublishedProject.objects.filter(is_self_managed_access=True).update(access_policy=AccessPolicy.CONTRIBUTOR_REVIEW)


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0046_auto_20210504_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeproject',
            name='access_policy',
            field=models.SmallIntegerField(
                choices=[(0, 'Open'), (1, 'Restricted'), (2, 'Credentialed'), (3, 'Contributor Review')],
                default=AccessPolicy(0),
            ),
        ),
        migrations.AlterField(
            model_name='archivedproject',
            name='access_policy',
            field=models.SmallIntegerField(
                choices=[(0, 'Open'), (1, 'Restricted'), (2, 'Credentialed'), (3, 'Contributor Review')],
                default=AccessPolicy(0),
            ),
        ),
        migrations.AlterField(
            model_name='license',
            name='access_policy',
            field=models.PositiveSmallIntegerField(
                choices=[(0, 'Open'), (1, 'Restricted'), (2, 'Credentialed'), (3, 'Contributor Review')],
                default=AccessPolicy(0),
            ),
        ),
        migrations.AlterField(
            model_name='publishedproject',
            name='access_policy',
            field=models.SmallIntegerField(
                choices=[(0, 'Open'), (1, 'Restricted'), (2, 'Credentialed'), (3, 'Contributor Review')],
                default=AccessPolicy(0),
            ),
        ),
        migrations.RunPython(migrate_forward),
        migrations.RemoveField(
            model_name='activeproject',
            name='is_self_managed_access',
        ),
        migrations.RemoveField(
            model_name='archivedproject',
            name='is_self_managed_access',
        ),
        migrations.RemoveField(
            model_name='publishedproject',
            name='is_self_managed_access',
        ),
    ]
