# Generated by Django 2.2.24 on 2021-09-24 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0046_auto_20210504_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legacyproject',
            name='contact_email',
            field=models.EmailField(default='contact@physionet.org', max_length=255),
        ),
    ]
