# Generated by Django 2.2.24 on 2021-09-29 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0046_auto_20210504_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeproject',
            name='allow_file_downloads',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='archivedproject',
            name='allow_file_downloads',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='publishedproject',
            name='allow_file_downloads',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
