# Generated by Django 2.2.24 on 2021-11-08 11:51

import project.modelcomponents.fields
import project.modelcomponents.metadata
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0046_auto_20210504_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeproject',
            name='ethical_approval',
            field=models.FileField(
                blank=True, null=True, upload_to=project.modelcomponents.metadata.ethical_approval_path
            ),
        ),
        migrations.AddField(
            model_name='activeproject',
            name='explanation',
            field=project.modelcomponents.fields.SafeHTMLField(blank=True),
        ),
        migrations.AddField(
            model_name='activeproject',
            name='other_approvals',
            field=models.FileField(
                blank=True, null=True, upload_to=project.modelcomponents.metadata.other_approvals_path
            ),
        ),
        migrations.AddField(
            model_name='archivedproject',
            name='ethical_approval',
            field=models.FileField(
                blank=True, null=True, upload_to=project.modelcomponents.metadata.ethical_approval_path
            ),
        ),
        migrations.AddField(
            model_name='archivedproject',
            name='explanation',
            field=project.modelcomponents.fields.SafeHTMLField(blank=True),
        ),
        migrations.AddField(
            model_name='archivedproject',
            name='other_approvals',
            field=models.FileField(
                blank=True, null=True, upload_to=project.modelcomponents.metadata.other_approvals_path
            ),
        ),
        migrations.AddField(
            model_name='editlog',
            name='necessary_approvals',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='publishedproject',
            name='ethical_approval',
            field=models.FileField(
                blank=True, null=True, upload_to=project.modelcomponents.metadata.ethical_approval_path
            ),
        ),
        migrations.AddField(
            model_name='publishedproject',
            name='explanation',
            field=project.modelcomponents.fields.SafeHTMLField(blank=True),
        ),
        migrations.AddField(
            model_name='publishedproject',
            name='other_approvals',
            field=models.FileField(
                blank=True, null=True, upload_to=project.modelcomponents.metadata.other_approvals_path
            ),
        ),
    ]
