# Generated by Django 2.2.24 on 2021-12-21 13:26
from itertools import chain

from django.db import migrations, models


def migrate_forward(apps, schema_editor):
    ActiveProject = apps.get_model('project', 'ActiveProject')
    ArchivedProject = apps.get_model('project', 'ActiveProject')
    PublishProject = apps.get_model('project', 'ActiveProject')
    TrainingType = apps.get_model('user', 'TrainingType')

    training_type = TrainingType.objects.first()

    for project in chain(ActiveProject.objects.all(), ArchivedProject.objects.all(), PublishProject.objects.all()):
        project.required_trainings.add(training_type)


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0034_auto_20211215_0859'),
        ('project', '0046_auto_20210504_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeproject',
            name='required_trainings',
            field=models.ManyToManyField(related_name='activeproject', to='user.TrainingType'),
        ),
        migrations.AddField(
            model_name='archivedproject',
            name='required_trainings',
            field=models.ManyToManyField(related_name='archivedproject', to='user.TrainingType'),
        ),
        migrations.AddField(
            model_name='publishedproject',
            name='required_trainings',
            field=models.ManyToManyField(related_name='publishedproject', to='user.TrainingType'),
        ),
        migrations.RunPython(migrate_forward),
    ]
