# Generated by Django 2.2.24 on 2021-10-14 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('project', '0047_accesslog_gcplog_log'), ('project', '0048_auto_20211014_0557')]

    dependencies = [
        ('project', '0046_auto_20210504_1504'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('ACCESS', 'Access'), ('GCP', 'GCP')], editable=False, max_length=64)),
                ('data', models.TextField(max_length=512)),
                ('count', models.PositiveIntegerField(default=1)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('last_access_datetime', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('object_id', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('project.log',),
        ),
        migrations.CreateModel(
            name='GCPLog',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('project.log',),
        ),
    ]
