# Generated by Django 2.2.24 on 2021-11-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0046_auto_20210504_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportingDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='activeproject',
            name='ethics_statement',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='archivedproject',
            name='ethics_statement',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='editlog',
            name='ethics_included',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='publishedproject',
            name='ethics_statement',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
