# Generated by Django 2.2.24 on 2021-11-29 09:27

from django.db import migrations, models
from project.modelcomponents.access import AccessPolicy
from project.modelcomponents.fields import SafeHTMLField


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0046_auto_20210504_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeproject',
            name='access_policy',
            field=models.SmallIntegerField(
                choices=[(0, 'Open'), (1, 'Restricted'), (2, 'Credentialed'), (3, 'Contributor Review')],
                default=AccessPolicy(0),
            ),
        ),
        migrations.AlterField(
            model_name='archivedproject',
            name='access_policy',
            field=models.SmallIntegerField(
                choices=[(0, 'Open'), (1, 'Restricted'), (2, 'Credentialed'), (3, 'Contributor Review')],
                default=AccessPolicy(0),
            ),
        ),
        migrations.AlterField(
            model_name='license',
            name='access_policy',
            field=models.PositiveSmallIntegerField(
                choices=[(0, 'Open'), (1, 'Restricted'), (2, 'Credentialed'), (3, 'Contributor Review')],
                default=AccessPolicy(0),
            ),
        ),
        migrations.AlterField(
            model_name='publishedproject',
            name='access_policy',
            field=models.SmallIntegerField(
                choices=[(0, 'Open'), (1, 'Restricted'), (2, 'Credentialed'), (3, 'Contributor Review')],
                default=AccessPolicy(0),
            ),
        ),
        migrations.AddField(
            model_name='license',
            name='access_request_template',
            field=SafeHTMLField(blank=True, default=''),
        ),
    ]
