# Generated by Django 2.2.24 on 2021-12-01 08:56

from django.db import migrations

import project.modelcomponents.fields


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0047_auto_20211129_0427'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='access_request_template',
            field=project.modelcomponents.fields.SafeHTMLField(blank=True, default=''),
        ),
        migrations.RemoveField(
            model_name='activeproject',
            name='self_managed_dua',
        ),
        migrations.RemoveField(
            model_name='activeproject',
            name='self_managed_request_template',
        ),
        migrations.RemoveField(
            model_name='archivedproject',
            name='self_managed_dua',
        ),
        migrations.RemoveField(
            model_name='archivedproject',
            name='self_managed_request_template',
        ),
        migrations.RemoveField(
            model_name='publishedproject',
            name='self_managed_dua',
        ),
        migrations.RemoveField(
            model_name='publishedproject',
            name='self_managed_request_template',
        ),
    ]
