# Generated by Django 2.2.24 on 2021-10-28 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0047_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='page',
            field=models.CharField(choices=[('ABOUT', 'about'), ('SHARE', 'share')], max_length=16),
        ),
    ]
