# Generated by Django 2.2.24 on 2021-11-04 08:41

import project.modelcomponents.metadata
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ('project', '0048_editlog_necessary_approvals_auto_20211104_0343'),
        ('project', '0049_auto_20211104_0343'),
    ]

    dependencies = [
        ('project', '0047_auto_20211103_0307'),
    ]

    operations = [
        migrations.AddField(
            model_name='editlog',
            name='necessary_approvals',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='activeproject',
            name='data_sharing_agreement',
            field=models.FileField(
                blank=True, null=True, upload_to=project.modelcomponents.metadata.data_sharing_agreement_path
            ),
        ),
        migrations.AlterField(
            model_name='activeproject',
            name='reb_approval_letter',
            field=models.FileField(
                blank=True, null=True, upload_to=project.modelcomponents.metadata.reb_approval_letter_path
            ),
        ),
        migrations.AlterField(
            model_name='archivedproject',
            name='data_sharing_agreement',
            field=models.FileField(
                blank=True, null=True, upload_to=project.modelcomponents.metadata.data_sharing_agreement_path
            ),
        ),
        migrations.AlterField(
            model_name='archivedproject',
            name='reb_approval_letter',
            field=models.FileField(
                blank=True, null=True, upload_to=project.modelcomponents.metadata.reb_approval_letter_path
            ),
        ),
        migrations.AlterField(
            model_name='publishedproject',
            name='data_sharing_agreement',
            field=models.FileField(
                blank=True, null=True, upload_to=project.modelcomponents.metadata.data_sharing_agreement_path
            ),
        ),
        migrations.AlterField(
            model_name='publishedproject',
            name='reb_approval_letter',
            field=models.FileField(
                blank=True, null=True, upload_to=project.modelcomponents.metadata.reb_approval_letter_path
            ),
        ),
        migrations.AlterField(
            model_name='activeproject',
            name='data_sharing_agreement',
            field=models.FileField(
                blank=True, null=True, upload_to=project.modelcomponents.metadata.data_sharing_agreement_path
            ),
        ),
        migrations.AlterField(
            model_name='activeproject',
            name='reb_approval_letter',
            field=models.FileField(
                blank=True, null=True, upload_to=project.modelcomponents.metadata.reb_approval_letter_path
            ),
        ),
        migrations.AlterField(
            model_name='archivedproject',
            name='data_sharing_agreement',
            field=models.FileField(
                blank=True, null=True, upload_to=project.modelcomponents.metadata.data_sharing_agreement_path
            ),
        ),
        migrations.AlterField(
            model_name='archivedproject',
            name='reb_approval_letter',
            field=models.FileField(
                blank=True, null=True, upload_to=project.modelcomponents.metadata.reb_approval_letter_path
            ),
        ),
        migrations.AlterField(
            model_name='publishedproject',
            name='data_sharing_agreement',
            field=models.FileField(
                blank=True, null=True, upload_to=project.modelcomponents.metadata.data_sharing_agreement_path
            ),
        ),
        migrations.AlterField(
            model_name='publishedproject',
            name='reb_approval_letter',
            field=models.FileField(
                blank=True, null=True, upload_to=project.modelcomponents.metadata.reb_approval_letter_path
            ),
        ),
    ]
