# Generated by Django 2.2.24 on 2021-11-03 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0047_auto_20211103_0307'),
    ]

    operations = [
        migrations.AddField(
            model_name='editlog',
            name='necessary_approvals',
            field=models.NullBooleanField(),
        ),
    ]
