# Generated by Django 2.2.25 on 2022-01-20 15:34

from django.db import migrations, models
import project.modelcomponents.fields
import project.modelcomponents.metadata


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('project', '0048_allow_file_downloads_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='activeproject',
            name='ethics_statement',
            field=project.modelcomponents.fields.SafeHTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='archivedproject',
            name='ethics_statement',
            field=project.modelcomponents.fields.SafeHTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='editlog',
            name='ethics_included',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='publishedproject',
            name='ethics_statement',
            field=project.modelcomponents.fields.SafeHTMLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='UploadedDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('document', models.FileField(upload_to=project.modelcomponents.metadata.get_document_path)),
                ('content_type', models.ForeignKey(on_delete=models.CASCADE, to='contenttypes.ContentType')),
                ('document_type', models.ForeignKey(on_delete=models.CASCADE, to='project.DocumentType')),
            ],
        ),
    ]
