# Generated by Django 2.2.24 on 2021-11-17 08:04

from django.db import migrations, models
import django.db.models.deletion
import project.modelcomponents.metadata


def migrate_forward(apps, schema_editor):
    ActiveProject = apps.get_model("project", "ActiveProject")
    ArchivedProject = apps.get_model("project", "ArchivedProject")
    PublishedProject = apps.get_model("project", "PublishedProject")

    ActiveProject.objects.update(ethics_statement="The authors declare no ethics concerns.")
    ArchivedProject.objects.update(ethics_statement="The authors declare no ethics concerns.")
    PublishedProject.objects.update(ethics_statement="The authors declare no ethics concerns.")


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('project', '0048_allow_file_downloads_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='activeproject',
            name='ethics_statement',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='archivedproject',
            name='ethics_statement',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='editlog',
            name='ethics_included',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='publishedproject',
            name='ethics_statement',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.CreateModel(
            name='UploadedDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('document', models.FileField(upload_to=project.modelcomponents.metadata.get_document_path)),
                (
                    'content_type',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
                ),
                (
                    'document_type',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.DocumentType'),
                ),
            ],
        ),
        migrations.RunPython(migrate_forward),
    ]
