# Generated by Django 2.2.26 on 2022-01-25 10:11

from django.db import migrations, models
import django.db.models.deletion
import project.modelcomponents.access
import project.modelcomponents.fields


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0049_auto_20211221_0826'),
    ]

    operations = [
        migrations.CreateModel(
            name='DUA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120)),
                ('html_content', project.modelcomponents.fields.SafeHTMLField(default='')),
                ('access_policy', models.PositiveSmallIntegerField(choices=[(0, 'Open'), (1, 'Restricted'), (2, 'Credentialed')], default=project.modelcomponents.access.AccessPolicy(0))),
                ('resource_types', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='activeproject',
            name='dua',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.DUA'),
        ),
        migrations.AddField(
            model_name='archivedproject',
            name='dua',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.DUA'),
        ),
        migrations.AddField(
            model_name='publishedproject',
            name='dua',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.DUA'),
        ),
    ]
