# Generated by Django 2.2.25 on 2022-01-18 11:09

from django.db import migrations
import project.modelcomponents.fields


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0049_auto_20211117_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeproject',
            name='ethics_statement',
            field=project.modelcomponents.fields.SafeHTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='archivedproject',
            name='ethics_statement',
            field=project.modelcomponents.fields.SafeHTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='publishedproject',
            name='ethics_statement',
            field=project.modelcomponents.fields.SafeHTMLField(blank=True),
        ),
    ]
