# Generated by Django 2.2.26 on 2022-02-07 10:49

from django.db import migrations, models
import project.modelcomponents.fields
import project.validators


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0050_auto_20220125_0511'),
    ]

    operations = [
        migrations.AddField(
            model_name='dua',
            name='access_template',
            field=project.modelcomponents.fields.SafeHTMLField(default=''),
        ),
        migrations.AddField(
            model_name='dua',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dua',
            name='project_types',
            field=models.ManyToManyField(related_name='duas', to='project.ProjectType'),
        ),
        migrations.AddField(
            model_name='dua',
            name='version',
            field=models.CharField(default='', max_length=15, validators=[project.validators.validate_version]),
        ),
        migrations.AddField(
            model_name='license',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='license',
            name='project_types',
            field=models.ManyToManyField(related_name='licenses', to='project.ProjectType'),
        ),
        migrations.AddField(
            model_name='license',
            name='version',
            field=models.CharField(default='', max_length=15, validators=[project.validators.validate_version]),
        ),
        migrations.AlterField(
            model_name='dua',
            name='slug',
            field=models.SlugField(max_length=120, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='dua',
            unique_together={('name', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='license',
            unique_together={('name', 'version')},
        ),
        migrations.RemoveField(
            model_name='dua',
            name='resource_types',
        ),
        migrations.RemoveField(
            model_name='license',
            name='dua_html_content',
        ),
        migrations.RemoveField(
            model_name='license',
            name='dua_name',
        ),
        migrations.RemoveField(
            model_name='license',
            name='resource_types',
        ),
    ]
