# Generated by Django 2.2.26 on 2022-01-25 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0050_auto_20220125_0511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='license',
            name='dua_html_content',
        ),
        migrations.RemoveField(
            model_name='license',
            name='dua_name',
        ),
    ]
