# Generated by Django 2.2.26 on 2022-02-07 09:48

from django.db import migrations, models
import project.modelcomponents.fields


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0050_auto_20220127_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='dua',
            name='access_template',
            field=project.modelcomponents.fields.SafeHTMLField(default=''),
        ),
        migrations.AddField(
            model_name='dua',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='license',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
