# Generated by Django 2.2.24 on 2022-01-05 17:19

from django.db import migrations

from project.modelcomponents.access import AccessPolicy


def migrate_forward(apps, schema_editor):
    pass


def migrate_backward(apps, schema_editor):
    ActiveProject = apps.get_model('project', 'ActiveProject')
    ArchivedProject = apps.get_model('project', 'ArchivedProject')
    PublishedProject = apps.get_model('project', 'PublishedProject')

    ActiveProject.objects.filter(access_policy=AccessPolicy.CONTRIBUTOR_REVIEW).update(
        is_self_managed_access=True
    )
    ArchivedProject.objects.filter(access_policy=AccessPolicy.CONTRIBUTOR_REVIEW).update(
        is_self_managed_access=True
    )
    PublishedProject.objects.filter(access_policy=AccessPolicy.CONTRIBUTOR_REVIEW).update(
        is_self_managed_access=True
    )


class Migration(migrations.Migration):
    MIGRATE_AFTER_INSTALL = True

    dependencies = [
        ('project', '0051_auto_20211129_0427'),
    ]

    operations = [
        migrations.RunPython(migrate_forward, migrate_backward),
        migrations.RemoveField(
            model_name='activeproject',
            name='is_self_managed_access',
        ),
        migrations.RemoveField(
            model_name='activeproject',
            name='self_managed_dua',
        ),
        migrations.RemoveField(
            model_name='activeproject',
            name='self_managed_request_template',
        ),
        migrations.RemoveField(
            model_name='archivedproject',
            name='is_self_managed_access',
        ),
        migrations.RemoveField(
            model_name='archivedproject',
            name='self_managed_dua',
        ),
        migrations.RemoveField(
            model_name='archivedproject',
            name='self_managed_request_template',
        ),
        migrations.RemoveField(
            model_name='publishedproject',
            name='is_self_managed_access',
        ),
        migrations.RemoveField(
            model_name='publishedproject',
            name='self_managed_dua',
        ),
        migrations.RemoveField(
            model_name='publishedproject',
            name='self_managed_request_template',
        ),
    ]
