# Generated by Django 2.2.27 on 2022-02-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0052_auto_20220105_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataaccessrequest',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
