# Generated by Django 2.2.24 on 2021-10-21 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0053_accesslog_gcplog_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='logs',
                to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
