# Generated by Django 2.2.24 on 2021-12-21 13:26
from itertools import chain

from django.db import migrations, models

from project.modelcomponents.access import AccessPolicy


def migrate_forward(apps, schema_editor):
    ActiveProject = apps.get_model('project', 'ActiveProject')
    ArchivedProject = apps.get_model('project', 'ArchivedProject')
    PublishedProject = apps.get_model('project', 'PublishedProject')
    TrainingType = apps.get_model('user', 'TrainingType')

    training_type = TrainingType.objects.first()

    filter = models.Q(access_policy__gte=AccessPolicy.CREDENTIALED)
    for project in chain(
        ActiveProject.objects.filter(filter),
        ArchivedProject.objects.filter(filter),
        PublishedProject.objects.filter(filter)
    ):
        project.required_training.add(training_type)


def migrate_backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0035_training_1'),
        ('project', '0054_auto_20211021_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeproject',
            name='required_training',
            field=models.ManyToManyField(related_name='activeproject', to='user.TrainingType'),
        ),
        migrations.AddField(
            model_name='archivedproject',
            name='required_training',
            field=models.ManyToManyField(related_name='archivedproject', to='user.TrainingType'),
        ),
        migrations.AddField(
            model_name='publishedproject',
            name='required_training',
            field=models.ManyToManyField(related_name='publishedproject', to='user.TrainingType'),
        ),
        migrations.RunPython(migrate_forward, migrate_backward),
    ]
