# Generated by Django 2.2.27 on 2022-03-22 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0058_license_dua_2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activeproject',
            old_name='required_training',
            new_name='required_trainings',
        ),
        migrations.RenameField(
            model_name='archivedproject',
            old_name='required_training',
            new_name='required_trainings',
        ),
        migrations.RenameField(
            model_name='publishedproject',
            old_name='required_training',
            new_name='required_trainings',
        ),
    ]
