# Generated by Django 2.2.27 on 2022-02-24 11:31

from django.db import migrations, models
import django.db.models.deletion
import project.modelcomponents.access
import project.modelcomponents.fields
import project.validators


def migrate_forward(apps, schema_editor):
    ...


def migrate_backward(apps, schema_editor):
    License = apps.get_model('project', 'License')

    for license in License.objects.all():
        license.resource_types = ','.join(str(pk) for pk in license.project_types.values_list('pk', flat=True))
        license.save()


class Migration(migrations.Migration):
    MIGRATE_AFTER_INSTALL = True

    dependencies = [
        ('project', '0058_license_dua_1'),
    ]

    operations = [
        migrations.RunPython(migrate_forward, migrate_backward),
        migrations.AlterField(
            model_name='license',
            name='resource_types',
            field=models.CharField(default='', null=True, max_length=100),
        ),
        migrations.RemoveField(
            model_name='license',
            name='access_request_template',
        ),
        migrations.RemoveField(
            model_name='license',
            name='dua_html_content',
        ),
        migrations.RemoveField(
            model_name='license',
            name='dua_name',
        ),
        migrations.RemoveField(
            model_name='license',
            name='resource_types',
        ),
    ]
