# Generated by Django 2.2.27 on 2022-03-22 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    MIGRATE_AFTER_INSTALL = True

    dependencies = [
        ('project', '0059_license_dua_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activeproject',
            name='required_training',
        ),
        migrations.RemoveField(
            model_name='archivedproject',
            name='required_training',
        ),
        migrations.RemoveField(
            model_name='publishedproject',
            name='required_training',
        ),
        migrations.AlterField(
            model_name='activeproject',
            name='required_trainings',
            field=models.ManyToManyField(related_name='activeproject', to='user.TrainingType'),
        ),
        migrations.AlterField(
            model_name='archivedproject',
            name='required_trainings',
            field=models.ManyToManyField(related_name='archivedproject', to='user.TrainingType'),
        ),
        migrations.AlterField(
            model_name='publishedproject',
            name='required_trainings',
            field=models.ManyToManyField(related_name='publishedproject', to='user.TrainingType'),
        ),
    ]
