# Generated by Django 2.2.27 on 2022-03-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0060_auto_20220322_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dua',
            name='slug',
            field=models.SlugField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='license',
            name='slug',
            field=models.SlugField(max_length=120, unique=True),
        ),
    ]
