# Generated by Django 2.2.27 on 2022-03-30 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0062_auto_20220221_0347'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesslog',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='dua',
            options={'default_permissions': ('add',)},
        ),
        migrations.AlterModelOptions(
            name='gcplog',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='license',
            options={'default_permissions': ('add',)},
        ),
        migrations.AlterModelOptions(
            name='log',
            options={'default_permissions': ()},
        ),
    ]
