# Generated by Django 2.2.28 on 2022-05-29 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0062_auto_20220221_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorinvitation',
            name='response',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='copyeditlog',
            name='made_changes',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='editlog',
            name='data_machine_readable',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='editlog',
            name='ethics_included',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='editlog',
            name='no_phi',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='editlog',
            name='open_format',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='editlog',
            name='pn_suitable',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='editlog',
            name='reusable',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='editlog',
            name='soundly_produced',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='editlog',
            name='well_described',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storagerequest',
            name='response',
            field=models.BooleanField(null=True),
        ),
    ]
