# Generated by Django 3.1.14 on 2022-12-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0063_auto_20220528_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeproject',
            name='embargo_files_days',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='archivedproject',
            name='embargo_files_days',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='publishedproject',
            name='embargo_files_days',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
    ]
