# Generated by Django 2.2.27 on 2022-03-30 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0063_auto_20220330_0411'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activeproject',
            options={'default_permissions': ('view',)},
        ),
        migrations.AlterModelOptions(
            name='archivedproject',
            options={'default_permissions': ('view',)},
        ),
    ]
