# Generated by Django 3.1.14 on 2022-11-09 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0063_auto_20220528_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataUseAgreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_copy_right_permission', models.PositiveSmallIntegerField(
                    choices=[(0, 'No'), (1, 'Yes'),(2, 'NA')])),
                ('has_human_subject_data', models.PositiveSmallIntegerField(
                    choices=[(0, 'No'), (1, 'Yes'), (2, 'NA')])),
                ('has_phi', models.PositiveSmallIntegerField(choices=[(0, 'No'), (1, 'Yes'), (2, 'NA')])),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='project.activeproject')),
            ],
        ),
    ]
