# Generated by Django 3.1.14 on 2023-01-09 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0064_auto_20221209_1108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activeproject',
            options={'default_permissions': ('change',),
                     'permissions': [('can_assign_editor', 'Can assign editor'),
                                     ('can_edit_activeprojects', 'Can edit ActiveProjects')]},
        ),
    ]
