# Generated by Django 3.1.14 on 2023-01-09 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0064_auto_20221209_1108'),
        ('project', '0064_auto_20221209_1300'),
    ]

    operations = [
    ]
