# Generated by Django 3.1.14 on 2023-01-11 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0066_auto_20230111_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeprojecttraining',
            name='temporary',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='archivedprojecttraining',
            name='temporary',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='publishedprojecttraining',
            name='temporary',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
