# Generated by Django 4.1.5 on 2023-01-26 03:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0050_alter_trainingtype_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0066_migrate_references_to_use_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeproject',
            name='core_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='%(class)ss', to='project.coreproject'),
        ),
        migrations.AlterField(
            model_name='activeproject',
            name='editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='editing_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activeproject',
            name='parent_projects',
            field=models.ManyToManyField(blank=True, related_name='derived_%(class)ss', to='project.publishedproject'),
        ),
        migrations.AlterField(
            model_name='activeproject',
            name='programming_languages',
            field=models.ManyToManyField(blank=True, related_name='%(class)ss', to='project.programminglanguage'),
        ),
        migrations.AlterField(
            model_name='activeproject',
            name='required_trainings',
            field=models.ManyToManyField(related_name='%(class)s', to='user.trainingtype'),
        ),
        migrations.AlterField(
            model_name='activeproject',
            name='resource_type',
            field=models.ForeignKey(db_column='resource_type', on_delete=django.db.models.deletion.PROTECT,
                                    related_name='%(class)ss', to='project.projecttype'),
        ),
        migrations.AlterField(
            model_name='archivedproject',
            name='core_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='%(class)ss', to='project.coreproject'),
        ),
        migrations.AlterField(
            model_name='archivedproject',
            name='editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='editing_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='archivedproject',
            name='parent_projects',
            field=models.ManyToManyField(blank=True, related_name='derived_%(class)ss', to='project.publishedproject'),
        ),
        migrations.AlterField(
            model_name='archivedproject',
            name='programming_languages',
            field=models.ManyToManyField(blank=True, related_name='%(class)ss', to='project.programminglanguage'),
        ),
        migrations.AlterField(
            model_name='archivedproject',
            name='required_trainings',
            field=models.ManyToManyField(related_name='%(class)s', to='user.trainingtype'),
        ),
        migrations.AlterField(
            model_name='archivedproject',
            name='resource_type',
            field=models.ForeignKey(db_column='resource_type', on_delete=django.db.models.deletion.PROTECT,
                                    related_name='%(class)ss', to='project.projecttype'),
        ),
        migrations.AlterField(
            model_name='author',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='authorinvitation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='%(class)ss', to='project.activeproject'),
        ),
        migrations.AlterField(
            model_name='dataaccess',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='%(class)ss', to='project.publishedproject'),
        ),
        migrations.AlterField(
            model_name='publishedauthor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='publishedproject',
            name='core_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='%(class)ss', to='project.coreproject'),
        ),
        migrations.AlterField(
            model_name='publishedproject',
            name='editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='editing_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='publishedproject',
            name='parent_projects',
            field=models.ManyToManyField(blank=True, related_name='derived_%(class)ss', to='project.publishedproject'),
        ),
        migrations.AlterField(
            model_name='publishedproject',
            name='programming_languages',
            field=models.ManyToManyField(blank=True, related_name='%(class)ss', to='project.programminglanguage'),
        ),
        migrations.AlterField(
            model_name='publishedproject',
            name='required_trainings',
            field=models.ManyToManyField(related_name='%(class)s', to='user.trainingtype'),
        ),
        migrations.AlterField(
            model_name='publishedproject',
            name='resource_type',
            field=models.ForeignKey(db_column='resource_type', on_delete=django.db.models.deletion.PROTECT,
                                    related_name='%(class)ss', to='project.projecttype'),
        ),
        migrations.AlterField(
            model_name='storagerequest',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='%(class)ss', to='project.activeproject'),
        ),
    ]
