# Generated by Django 3.1.14 on 2023-01-18 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0066_migrate_references_to_use_order'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reference',
            unique_together={('description', 'object_id', 'order')},
        ),
    ]
