# Generated by Django 3.1.14 on 2022-11-29 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0067_alter_activeproject_core_project_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataUploadAgreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_copy_right_permission', models.PositiveSmallIntegerField(choices=[(0, 'Yes'), (1, 'No')])),
                ('has_human_subject_data', models.PositiveSmallIntegerField(choices=[(0, 'Yes'), (1, 'No')])),
                ('has_phi', models.PositiveSmallIntegerField(choices=[(0, 'Yes'), (1, 'No'), (2, 'NA')])),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                                 to='project.activeproject')),
            ],
        ),
    ]
