# Generated by Django 4.1.10 on 2023-08-29 19:13

from django.db import migrations, models


def migrate_forward(apps, schema_editor):
    pass


def migrate_backward(apps, schema_editor):
    ActiveProject = apps.get_model('project', 'ActiveProject')
    ArchivedProject = apps.get_model('project', 'ArchivedProject')
    for model in (ActiveProject, ArchivedProject):
        for project in model.objects.all():
            if project.is_new_version:
                project.version_order = 1
            else:
                project.version_order = 0
            project.save(update_fields=['version_order'])


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0068_auto_20230711_1651"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activeproject",
            name="version_order",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="archivedproject",
            name="version_order",
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.RunPython(migrate_forward, reverse_code=migrate_backward),
    ]
