# Generated by Django 4.1.10 on 2023-08-29 19:13

from django.db import migrations


class Migration(migrations.Migration):
    MIGRATE_AFTER_INSTALL = True

    dependencies = [
        ("project", "0069_unpublishedproject_version_order_1"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activeproject",
            name="version_order",
        ),
        migrations.RemoveField(
            model_name="archivedproject",
            name="version_order",
        ),
    ]
