# Generated by Django 4.1.10 on 2023-11-20 20:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0070_unpublishedproject_version_order_2"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activeproject",
            options={
                "default_permissions": ("change",),
                "ordering": ("title", "creation_datetime"),
                "permissions": [
                    ("can_assign_editor", "Can assign editor"),
                    ("can_edit_activeprojects", "Can edit ActiveProjects"),
                ],
            },
        ),
        migrations.AlterModelOptions(
            name="publishedproject",
            options={
                "default_permissions": ("change",),
                "ordering": ("title", "version_order"),
                "permissions": [
                    ("can_edit_featured_content", "Can edit featured content"),
                    ("can_view_access_logs", "Can view access logs"),
                    ("can_view_project_guidelines", "Can view project guidelines"),
                    ("can_view_stats", "Can view stats"),
                ],
            },
        ),
    ]
