# Generated by Django 4.1.10 on 2023-11-21 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0071_alter_activeproject_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AWS",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bucket_name", models.CharField(max_length=150, null=True)),
                ("is_private", models.BooleanField(default=False)),
                ("sent_zip", models.BooleanField(default=False)),
                ("sent_files", models.BooleanField(default=False)),
                ("creation_datetime", models.DateTimeField(auto_now_add=True)),
                ("finished_datetime", models.DateTimeField(null=True)),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aws",
                        to="project.publishedproject",
                    ),
                ),
            ],
            options={
                "default_permissions": (),
            },
        ),
    ]
