# Generated by Django 4.1.10 on 2023-12-01 07:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0072_aws"),
    ]

    operations = [
        migrations.AddField(
            model_name="activeproject",
            name="archive_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
