# Generated by Django 4.1.10 on 2024-09-16 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0077_fix_some_references"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessPointUser",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("aws_id", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="AccessPoint",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "aws",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_points",
                        to="project.aws",
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        related_name="access_points", to="project.accesspointuser"
                    ),
                ),
            ],
        ),
    ]
