# Generated by Django 4.2.18 on 2025-03-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0078_delete_archivedproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataaccessrequest',
            name='collaborators',
            field=models.TextField(blank=True, help_text='List of collaborators (Name, email addresses)', null=True),
        ),
        migrations.AddField(
            model_name='dataaccessrequest',
            name='publications_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
