# Generated by Django 4.1.10 on 2025-03-14 17:46

from django.db import migrations
import project.modelcomponents.fields


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0078_delete_archivedproject"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataaccessrequest",
            name="lay_summary",
            field=project.modelcomponents.fields.SafeHTMLField(
                blank=True, max_length=5000, null=True
            ),
        ),
    ]
