# Generated by Django 4.1.10 on 2025-01-21 22:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("project", "0079_awsaccesspoint_awsaccesspointuser_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="awsaccesspointuser",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="awsaccesspointuser",
            name="aws",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="access_point_users",
                to="project.aws",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="awsaccesspointuser",
            unique_together={("user", "aws")},
        ),
    ]
