# Generated by Django 4.1.10 on 2025-01-21 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0081_alter_awsaccesspointuser_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="awsaccesspointuser",
            name="aws",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="access_point_users",
                to="project.aws",
            ),
        ),
    ]
