# Generated by Django 4.1.10 on 2025-02-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0082_alter_awsaccesspointuser_aws"),
    ]

    operations = [
        migrations.AlterField(
            model_name="awsaccesspoint",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
