# Generated by Django 4.2.21 on 2025-06-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0084_project_file_root'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeproject',
            name='georestricted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='publishedproject',
            name='georestricted',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
