# Generated by Django 4.2.22 on 2025-07-25 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0085_activeproject_georestricted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BigQueryDataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_name', models.CharField(max_length=128)),
                ('group_email', models.CharField(max_length=170)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bigquery_datasets', to='project.publishedproject')),
            ],
            options={
                'default_permissions': (),
                'unique_together': {('project', 'dataset_name')},
            },
        ),
    ]
