# Generated by Django 4.2.22 on 2025-10-07 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0085_activeproject_georestricted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeproject',
            name='archive_reason',
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (0, 'Rejected by editor'),
                    (1, 'Deleted by author'),
                    (2, 'Archived by editor')
                ],
                null=True
            ),
        ),
        migrations.AddField(
            model_name='activeproject',
            name='archive_reason_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
