# Generated by Django 4.2.26 on 2025-12-18 21:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0086_activeproject_archive_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="publishedproject",
            name="public_project_uuid",
            field=models.UUIDField(
                db_index=True,
                editable=False,
                help_text="Persistent, public identifier for published projects.",
                null=True,
            ),
        ),
    ]
