# Generated by Django 4.2.26 on 2025-11-27 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0086_activeproject_archive_reason_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FederatedProject",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(help_text="Project slug on the source site")),
                (
                    "version",
                    models.CharField(help_text="Project version", max_length=15),
                ),
                ("title", models.CharField(help_text="Project title", max_length=200)),
                ("abstract", models.TextField(help_text="Project abstract")),
                (
                    "doi",
                    models.CharField(
                        blank=True,
                        help_text="Digital Object Identifier",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        help_text="URL to project page on source site", max_length=500
                    ),
                ),
                (
                    "resource_type",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Resource type: 0=Database, 1=Software, 2=Challenge, 3=Model",
                        null=True,
                    ),
                ),
                (
                    "access_policy",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Access policy: 0=Open, 1=Restricted, 2=Credentialed, 3=Contributor Review",
                        null=True,
                    ),
                ),
                (
                    "publish_datetime",
                    models.DateTimeField(
                        help_text="When the project was published on source site"
                    ),
                ),
                (
                    "main_storage_size",
                    models.BigIntegerField(
                        default=0, help_text="Storage size in bytes"
                    ),
                ),
                (
                    "topics",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='List of topic tags (e.g., ["ehr", "critical care"])',
                        null=True,
                    ),
                ),
                (
                    "last_fetched",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Last time this project metadata was updated",
                    ),
                ),
                (
                    "is_stale",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this project no longer exists on source site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Federated Project",
                "verbose_name_plural": "Federated Projects",
                "ordering": ["-publish_datetime", "title"],
            },
        ),
        migrations.CreateModel(
            name="FederatedSite",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_identifier",
                    models.SlugField(
                        help_text='Unique identifier for this site (e.g., "physionet-mit", "hdnx-uoft")',
                        unique=True,
                    ),
                ),
                (
                    "site_name",
                    models.CharField(
                        help_text='Display name for this site (e.g., "PhysioNet", "HealthDataNexus")',
                        max_length=200,
                    ),
                ),
                (
                    "api_base_url",
                    models.URLField(
                        help_text='Base URL for the federation API (e.g., "https://healthdatanexus.ca")',
                        max_length=500,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether to sync data from this site"
                    ),
                ),
                (
                    "last_sync_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of last successful sync",
                        null=True,
                    ),
                ),
                (
                    "last_sync_status",
                    models.CharField(
                        choices=[
                            ("never", "Never synced"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("in_progress", "In progress"),
                        ],
                        default="never",
                        help_text="Status of most recent sync attempt",
                        max_length=20,
                    ),
                ),
                (
                    "api_key",
                    models.CharField(
                        blank=True,
                        help_text="API key for authentication (optional)",
                        max_length=200,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Federated Site",
                "verbose_name_plural": "Federated Sites",
                "ordering": ["site_name"],
            },
        ),
        migrations.CreateModel(
            name="FederationSyncLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(help_text="When sync started")),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="When sync completed", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("partial", "Partial success"),
                        ],
                        help_text="Overall status of this sync",
                        max_length=20,
                    ),
                ),
                (
                    "projects_fetched",
                    models.IntegerField(
                        default=0, help_text="Total projects fetched from API"
                    ),
                ),
                (
                    "projects_created",
                    models.IntegerField(
                        default=0, help_text="New projects added to cache"
                    ),
                ),
                (
                    "projects_updated",
                    models.IntegerField(
                        default=0, help_text="Existing projects updated"
                    ),
                ),
                (
                    "projects_deleted",
                    models.IntegerField(
                        default=0, help_text="Projects marked as stale/deleted"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if sync failed"
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        help_text="The site that was synced",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_logs",
                        to="project.federatedsite",
                    ),
                ),
            ],
            options={
                "verbose_name": "Federation Sync Log",
                "verbose_name_plural": "Federation Sync Logs",
                "ordering": ["-started_at"],
            },
        ),
        migrations.AddIndex(
            model_name="federatedsite",
            index=models.Index(
                fields=["is_active", "last_sync_datetime"],
                name="project_fed_is_acti_ecf1b3_idx",
            ),
        ),
        migrations.AddField(
            model_name="federatedproject",
            name="source_site",
            field=models.ForeignKey(
                help_text="The federated site this project belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cached_projects",
                to="project.federatedsite",
            ),
        ),
        migrations.AddIndex(
            model_name="federationsynclog",
            index=models.Index(
                fields=["site", "-started_at"], name="project_fed_site_id_1eb618_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="federationsynclog",
            index=models.Index(
                fields=["status", "-started_at"], name="project_fed_status_4617ac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="federatedproject",
            index=models.Index(
                fields=["slug", "version"], name="project_fed_slug_5299d8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="federatedproject",
            index=models.Index(
                fields=["publish_datetime"], name="project_fed_publish_353ff3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="federatedproject",
            index=models.Index(
                fields=["resource_type"], name="project_fed_resourc_285dc0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="federatedproject",
            index=models.Index(fields=["title"], name="project_fed_title_2a665a_idx"),
        ),
        migrations.AddIndex(
            model_name="federatedproject",
            index=models.Index(
                fields=["is_stale"], name="project_fed_is_stal_bdd10f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="federatedproject",
            unique_together={("source_site", "slug", "version")},
        ),
    ]
