# Generated by Django 4.2.26 on 2026-01-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0087_anonymousaccess_hide_authors"),
    ]

    operations = [
        migrations.AddField(
            model_name="publishedproject",
            name="public_project_uuid",
            field=models.UUIDField(
                db_index=True,
                editable=False,
                help_text="Persistent, public identifier for published projects.",
                null=True,
            ),
        ),
    ]
