# Generated by Django 4.2.25 on 2026-02-10 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0087_anonymousaccess_hide_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeproject',
            name='is_on_hold',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
