# Generated by Django 4.2.25 on 2026-02-10 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    MIGRATE_AFTER_INSTALL = True

    dependencies = [
        ('project', '0088_activeproject_is_on_hold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeproject',
            name='is_on_hold',
            field=models.BooleanField(default=False),
        ),
    ]
