# Generated by Django 4.2.26 on 2026-01-21 00:01

import uuid

from django.db import migrations


def backfill_public_project_uuid(apps, schema_editor):
    """Generate UUID for all PublishedProject records that don't have one."""
    PublishedProject = apps.get_model('project', 'PublishedProject')
    for project in PublishedProject.objects.filter(public_project_uuid__isnull=True):
        project.public_project_uuid = uuid.uuid4()
        project.save(update_fields=['public_project_uuid'])


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0088_publishedproject_public_project_uuid"),
    ]

    operations = [
        migrations.RunPython(backfill_public_project_uuid, migrations.RunPython.noop),
    ]
