# Generated by Django 4.2.26 on 2026-01-21 00:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0089_backfill_public_project_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishedproject',
            name='public_project_uuid',
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                help_text='Persistent, public identifier for published projects.',
                unique=True,
            ),
        ),
    ]
