# Generated by Django 4.2.27 on 2026-02-24 18:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0089_alter_activeproject_is_on_hold'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishedproject',
            name='public_project_uuid',
            field=models.UUIDField(
                editable=False,
                help_text='Persistent, public identifier for published projects.',
                null=True,
            ),
        ),
    ]
