# Generated by Django 4.2.26 on 2026-01-06 17:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0087_anonymousaccess_hide_authors"),
        ("project", "0089_alter_publishedproject_public_project_uuid"),
    ]

    operations = []
