# Generated by Django 4.2.27 on 2026-02-24 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0089_alter_activeproject_is_on_hold'),
        ('project', '0090_alter_publishedproject_public_project_uuid'),
    ]

    operations = [
    ]
