# Generated by Django 4.2.25 on 2026-03-27 19:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0092_alter_publishedproject_public_project_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="publishedproject",
            name="submission_slug",
            field=models.SlugField(max_length=30, null=True),
        ),
    ]
