# Generated by Django 4.2.25 on 2026-03-27 19:57

import json
import os

from django.db import migrations, models


def populate_submission_slug(apps, schema_editor):
    # Determine historical (2019-2026) submission slugs from Task and
    # CompletedTask objects that were created at the time those
    # projects were published.  The signature for the task function
    # was:
    #
    #   def move_files_as_readonly(pid, dir_from, dir_to, make_zip)
    #
    # where `pid` was the integer ID of the PublishedProject,
    # `dir_from` was the name of the active project directory,
    # `dir_to` was the name of the published project directory,
    # and `make_zip` was 0 or 1.

    PublishedProject = apps.get_model('project', 'PublishedProject')
    Task = apps.get_model('background_task', 'Task')
    CompletedTask = apps.get_model('background_task', 'CompletedTask')

    TASK_NAMES = (
        'project.models.move_files_as_readonly',
        'project.modelcomponents.activeproject.move_files_as_readonly',
    )

    submission_slugs = {}

    for model in (CompletedTask, Task):
        for name in TASK_NAMES:
            for task in model.objects.filter(task_name=name):
                args, kwargs = json.loads(task.task_params)
                if isinstance(args[0], int) and isinstance(args[1], str):
                    submission_slugs[args[0]] = os.path.basename(args[1])

    for project in PublishedProject.objects.filter(submission_slug__isnull=True):
        try:
            project.submission_slug = submission_slugs[project.id]
        except KeyError:
            project.submission_slug = 'unknown_{}'.format(
                str(project.public_project_uuid)[:8]
            )
        project.save(update_fields=['submission_slug'])


class Migration(migrations.Migration):
    MIGRATE_AFTER_INSTALL = True

    dependencies = [
        ("background_task", "0001_initial"),
        ("project", "0093_publishedproject_submission_slug_1"),
    ]

    operations = [
        migrations.RunPython(
            populate_submission_slug,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="publishedproject",
            name="submission_slug",
            field=models.SlugField(max_length=30, unique=True),
        ),
    ]
