# Generated by Django 4.2.25 on 2026-03-26 21:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0094_publishedproject_submission_slug_2"),
    ]

    operations = [
        migrations.AddField(
            model_name="activeproject",
            name="main_storage_size",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="activeproject",
            name="checksums_valid_datetime",
            field=models.DateTimeField(null=True, blank=True),
        ),
    ]
