# Generated by Django 4.2.25 on 2026-03-06 17:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0094_publishedproject_submission_slug_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeproject',
            name='required_reviews',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
    ]
