# Generated by Django 4.2.25 on 2026-03-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):
    MIGRATE_AFTER_INSTALL = True

    dependencies = [
        ("project", "0095_activeproject_checksums_1"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activeproject",
            name="main_storage_size",
            field=models.BigIntegerField(default=0),
        ),
    ]
