# Generated by Django 4.2.20 on 2026-05-22 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0096_activeproject_checksums_2"),
    ]

    operations = [
        migrations.AddField(
            model_name="aws",
            name="access_disabled",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
