# Generated by Django 4.2.28 on 2026-05-05 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0096_activeproject_checksums_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='category',
            field=models.CharField(choices=[('ACCESS', 'Access'), ('GCP', 'GCP'), ('ENTITLEMENT_CHECK', 'Entitlement Check')], editable=False, max_length=64),  # noqa: E501
        ),
    ]
