# Generated by Django 4.2.25 on 2026-03-06 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0097_activeproject_required_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewerInvitation',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True,
                    serialize=False, verbose_name='ID')),
                ('invitation_datetime',
                    models.DateTimeField(auto_now_add=True)),
                ('response_datetime',
                    models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('review_deadline', models.DateField()),
                ('invited_by', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='sent_reviewer_invitations',
                    to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='reviewer_invitations',
                    to='project.activeproject')),
                ('reviewer', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='reviewer_invitations',
                    to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_permissions': (),
                'unique_together': {('project', 'reviewer')},
            },
        ),
        migrations.CreateModel(
            name='ExternalReview',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True,
                    serialize=False, verbose_name='ID')),
                ('recommendation',
                    models.PositiveSmallIntegerField(choices=[
                        (1, 'Accept'), (2, 'Minor Revisions'),
                        (3, 'Major Revisions'), (4, 'Reject'),
                    ])),
                ('comments_to_editor', models.TextField(
                    help_text='Private comments visible only '
                              'to the editor.')),
                ('comments_to_author', models.TextField(
                    help_text='Comments that may be shared '
                              'with the author.')),
                ('quality_of_writing',
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, choices=[
                            (1, '1 - Poor'),
                            (2, '2 - Below Average'),
                            (3, '3 - Average'),
                            (4, '4 - Good'),
                            (5, '5 - Excellent'),
                        ])),
                ('significance',
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, choices=[
                            (1, '1 - Poor'),
                            (2, '2 - Below Average'),
                            (3, '3 - Average'),
                            (4, '4 - Good'),
                            (5, '5 - Excellent'),
                        ])),
                ('technical_validity',
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, choices=[
                            (1, '1 - Poor'),
                            (2, '2 - Below Average'),
                            (3, '3 - Average'),
                            (4, '4 - Good'),
                            (5, '5 - Excellent'),
                        ])),
                ('submitted_datetime',
                    models.DateTimeField(auto_now_add=True)),
                ('invitation', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='review',
                    to='project.reviewerinvitation')),
            ],
            options={
                'default_permissions': (),
            },
        ),
    ]
