# Generated by Django 4.2.28 on 2026-05-05 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('project', '0097_alter_log_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntitlementCheckLog',
            fields=[
            ],
            options={
                'proxy': True,
                'default_permissions': (),
                'indexes': [],
                'constraints': [],
            },
            bases=('project.log',),
        ),
        migrations.AlterField(
            model_name='log',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='log',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
