# Generated by Django 4.2.20 on 2026-06-04 20:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0097_aws_access_disabled"),
        ("project", "0098_add_review_models"),
    ]

    operations = []
