# Generated by Django 4.2.29 on 2026-08-28 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0099_affiliation_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadAgreement',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID',
                )),
                ('accepted', models.BooleanField(
                    default=False,
                    help_text='Whether the upload agreement has been accepted',
                )),
                ('accepted_datetime', models.DateTimeField(
                    blank=True,
                    help_text='When the upload agreement was accepted',
                    null=True,
                )),
                ('no_human_subjects', models.BooleanField(
                    default=False,
                    help_text=(
                        'This project does not contain any data derived '
                        'from human subjects'
                    ),
                )),
                ('derived_data', models.BooleanField(
                    default=False,
                    help_text=(
                        'This project contains data derived from other '
                        'de-identified datasets'
                    ),
                )),
                ('human_subjects_deidentified', models.BooleanField(
                    default=False,
                    help_text=(
                        'This project contains data obtained from human '
                        'subjects, and all personally identifiable '
                        'information has been removed'
                    ),
                )),
                ('created_datetime', models.DateTimeField(
                    auto_now_add=True,
                )),
                ('updated_datetime', models.DateTimeField(
                    auto_now=True,
                )),
                ('author', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='upload_agreement',
                    to='project.author',
                )),
            ],
            options={
                'verbose_name': 'Upload Agreement',
                'verbose_name_plural': 'Upload Agreements',
                'db_table': 'project_uploadagreement',
            },
        ),
        migrations.AddConstraint(
            model_name='uploadagreement',
            constraint=models.CheckConstraint(
                check=models.Q(
                    ('no_human_subjects', True),
                    ('derived_data', True),
                    ('human_subjects_deidentified', True),
                    _connector='OR',
                ),
                name='at_least_one_data_type_selected',
                violation_error_message='Please select at least one option that applies to your project.',
            ),
        ),
    ]
