# Generated by Django 4.2.25 on 2026-09-09 19:29

from django.db import migrations, models


class Migration(migrations.Migration):
    MIGRATE_AFTER_INSTALL = True

    dependencies = [
        ("project", "0100_uploadagreement_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="publishedproject",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_latest_version", True)),
                fields=("core_project",),
                name="single_latest_version_per_core_project",
            ),
        ),
        migrations.AddConstraint(
            model_name="publishedproject",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_latest_version", True)),
                fields=("slug",),
                name="single_latest_version_per_slug",
            ),
        ),
    ]
