# Generated by Django 4.2.20 on 2026-09-22 20:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0099_merge_0097_aws_access_disabled_0098_add_review_models"),
        (
            "project",
            "0101_publishedproject_single_latest_version_per_core_project_and_more",
        ),
    ]

    operations = []
