# Generated by Django 4.2.20 on 2026-09-23 18:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "project",
            "0101_publishedproject_single_latest_version_per_core_project_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="aws",
            name="access_disabled",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
