# Generated by Django 5.2.17 on 2026-10-02 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0102_aws_access_disabled'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activeproject',
            options={
                'default_permissions': ('change',),
                'ordering': ('title', 'creation_datetime'),
                'permissions': [('can_assign_editor', 'Can assign editor'), ('can_edit_activeprojects',
                'Can edit ActiveProjects'), ('can_archive_project', 'Can archive ActiveProjects')]},
        ),
    ]
