# Generated by Django 4.2.22 on 2025-09-10 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import project.modelcomponents.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0085_activeproject_georestricted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_project_version', models.CharField(blank=True, default='', max_length=15)),
                ('target_filepath', models.CharField(help_text='Path to the target file being annotated', max_length=500)),
                ('target_modality', models.CharField(choices=[('image', 'image'), ('document', 'document')], db_index=True, max_length=32)),
                ('target_text', models.TextField(blank=True)),
                ('annotation_description', models.TextField(blank=True)),
                ('annotation_data', models.JSONField(default=dict, help_text='Annotation data following the PhysioNet annotation schema')),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'default_permissions': ('add', 'delete', 'change'),
            },
        ),
        migrations.CreateModel(
            name='DocumentAnnotation',
            fields=[
                ('annotation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='experimental.annotation')),
            ],
            bases=('experimental.annotation',),
        ),
        migrations.CreateModel(
            name='AnnotationCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', project.modelcomponents.fields.SafeHTMLField(blank=True)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experimental_annotation_collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_permissions': ('add', 'delete', 'change'),
            },
        ),
        migrations.AddField(
            model_name='annotation',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='experimental.annotationcollection'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experimental_annotations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='annotation',
            name='target_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experimental_annotations', to='project.publishedproject'),
        ),
        migrations.CreateModel(
            name='DocumentAnnotationDataType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_texts', models.JSONField(default=list)),
                ('annotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotation_data_types', to='experimental.documentannotation')),
            ],
        ),
    ]
