# Generated by Django 4.2.22 on 2025-09-10 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('experimental', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_texts', models.JSONField(default=list)),
            ],
        ),
        migrations.RemoveField(
            model_name='documentannotationdatatype',
            name='annotation',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='annotation_data',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='target_text',
        ),
        migrations.CreateModel(
            name='DocumentAnnotationData',
            fields=[
                ('annotationdata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='experimental.annotationdata')),
                ('target_text', models.TextField(blank=True)),
            ],
            bases=('experimental.annotationdata',),
        ),
        migrations.DeleteModel(
            name='DocumentAnnotation',
        ),
        migrations.DeleteModel(
            name='DocumentAnnotationDataType',
        ),
        migrations.AddField(
            model_name='annotationdata',
            name='annotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotation_data', to='experimental.annotation'),
        ),
    ]
