version: '3.9'

services:
  test:
    image: physionet:latest
    build: ..
    depends_on:
      - db
      - gcs
    environment:
      DJANGO_SETTINGS_MODULE: physionet.settings.settings
      DB_HOST: db
      DB_NAME: physionet_test
      MEDIA_ROOT: /data/pn-media
      STATIC_ROOT: /data/pn-static
      GCS_HOST: http://gcs:4443
    env_file: ../.env.example
    entrypoint: ./docker/test-entrypoint.sh
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: physionet
      POSTGRES_PASSWORD: password
      POSTGRES_DB: physionet_test

  gcs:
    image: fsouza/fake-gcs-server
    command: ["-scheme", "http", "-port", "4443", "-external-url", "http://0.0.0.0:4443", "-backend", "memory"]
