# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-12-25 17:58
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('content', ckeditor.fields.RichTextField()),
                ('publish_datetime', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField(blank=True, default='')),
            ],
        ),
    ]
