# Generated by Django 2.1.7 on 2019-04-17 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_gcp'),
        ('notification', '0002_auto_20190405_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='project.PublishedProject'),
        ),
    ]
