# Generated by Django 2.1.7 on 2019-05-02 16:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_news_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='guid',
            field=models.CharField(default=uuid.uuid4, max_length=64),
        ),
    ]
