# Generated by Django 2.1.9 on 2019-07-23 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification', '0005_auto_20190502_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to=settings.AUTH_USER_MODEL),
        ),
    ]
