# Generated by Django 2.2.27 on 2022-02-21 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0006_auto_20191218_1304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'default_permissions': ('change',)},
        ),
    ]
