# Generated by Django 4.1.10 on 2023-11-29 19:39

from django.db import migrations, models


def set_default_slugs(apps, schema_editor):
    News = apps.get_model('notification', 'News')
    for news in News.objects.all():
        news.slug = str(news.id)
        news.save()


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0007_auto_20220221_0332"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="slug",
            field=models.SlugField(max_length=100, null=True),
        ),
        migrations.RunPython(set_default_slugs, reverse_code=migrations.RunPython.noop),
    ]
