# Generated by Django 4.1.10 on 2023-11-29 20:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0008_news_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="slug",
            field=models.SlugField(max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
