# Generated by Django 4.2.20 on 2025-03-27 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notification", "0010_news_link_all_versions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="title",
            field=models.CharField(max_length=150),
        ),
    ]
