# Generated by Django 4.2.25 on 2026-02-23 00:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification', '0011_alter_news_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'notification_type',
                    models.IntegerField(
                        choices=[
                            (1, 'Author invitation'),
                            (2, 'Invitation response'),
                            (3, 'Editor decision'),
                            (4, 'Project published'),
                            (5, 'Project submission'),
                            (6, 'Editor assignment'),
                            (7, 'Copyedit'),
                            (8, 'Storage request'),
                            (9, 'Credential decision'),
                            (10, 'Cohost invitation'),
                            (11, 'Cohost response'),
                            (12, 'Generic'),
                        ],
                        default=12,
                    ),
                ),
                ('message', models.CharField(max_length=500)),
                (
                    'url',
                    models.CharField(
                        blank=True, default='', max_length=500
                    ),
                ),
                ('is_read', models.BooleanField(default=False)),
                (
                    'created_datetime',
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    'actor',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='acted_notifications',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'recipient',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='notifications',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['-created_datetime'],
                'indexes': [
                    models.Index(
                        fields=[
                            'recipient',
                            'is_read',
                            '-created_datetime',
                        ],
                        name='notif_recipient_unread_idx',
                    ),
                ],
            },
        ),
    ]
