# Generated by Django 3.2.16 on 2023-02-16 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventapplications'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventparticipant',
            name='is_cohost',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
