# Generated by Django 3.2.16 on 2023-02-22 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0067_alter_activeproject_core_project_and_more'),
        ('events', '0004_eventparticipant_is_cohost'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(choices=[('GBQ', 'Google BigQuery'), ('RE', 'Research Environment')],
                                                 default='GBQ', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('added_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                              to='project.publishedproject')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                            related_name='datasets', to='events.event')),
            ],
        ),
    ]
