# Generated by Django 3.2.16 on 2023-02-24 14:35

from django.db import migrations
import project.modelcomponents.fields


def migrate_forward(apps, schema_editor):
    Event = apps.get_model('events', 'Event')
    for event in Event.objects.all():
        event.full_clean()
        event.save()


def migrate_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_event_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=project.modelcomponents.fields.SafeHTMLField(blank=True, max_length=10000, null=True),
        ),
        migrations.RunPython(migrate_forward, reverse_code=migrate_reverse),

    ]
