# Generated by Django 4.1.13 on 2024-02-08 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_event_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CohostInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('request_datetime', models.DateTimeField(auto_now_add=True)),
                ('response_datetime', models.DateTimeField(null=True)),
                ('response', models.BooleanField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
            options={
                'default_permissions': (),
            },
        ),
    ]
