# Generated by Django 4.1.9 on 2023-11-17 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_event_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'permissions': [('view_all_events', 'Can view all events in the console'), ('invite_event_host', 'Can grant event host status to a user'), ('view_event_menu', 'Can view event menu in the navbar')]},
        ),
    ]
