# Generated by Django 4.2.18 on 2025-02-19 02:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("events", "0010_alter_event_options"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="eventapplication",
            unique_together={("user", "event")},
        ),
    ]
