# Generated by Django 4.2.18 on 2025-03-14 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0010_alter_event_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="gcp_billing_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
