# Generated by Django 4.2.22 on 2025-09-07 21:03

import annotation.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import project.modelcomponents.fields
import project.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0085_activeproject_georestricted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', project.modelcomponents.fields.SafeHTMLField(blank=True)),
                ('modality', models.CharField(choices=[('image', 'image'), ('video', 'video'), ('time_series', 'time_series'), ('text', 'text'), ('label', 'label')], max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'default_permissions': ('add', 'delete', 'change'),
            },
        ),
        migrations.CreateModel(
            name='AnnotationCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, validators=[project.validators.validate_title])),
                ('description', project.modelcomponents.fields.SafeHTMLField(blank=True)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='project.publishedproject')),
            ],
            options={
                'default_permissions': ('add', 'delete', 'change'),
            },
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(validators=[annotation.validators.validate_annotation_data])),
                ('modality', models.CharField(db_index=True, max_length=32)),
                ('label_text', models.CharField(blank=True, db_index=True, max_length=255)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('annotation_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='annotations', to='annotation.annotationtype')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='annotation.annotationcollection')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_permissions': ('add', 'delete', 'change'),
                'indexes': [models.Index(fields=['annotation_type', 'collection'], name='annotation__annotat_e5d7da_idx'), models.Index(fields=['modality', 'label_text'], name='annotation__modalit_1e5a6d_idx')],
            },
        ),
    ]
