# Generated by Django 4.2.25 on 2025-11-10 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0086_activeproject_archive_reason_and_more'),
        ('annotation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='annotation_type',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='annotations',
                to='annotation.annotationtype'
            ),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='collection',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='annotations',
                to='annotation.annotationcollection'
            ),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='location',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='annotation',
                to='annotation.baselocation'
            ),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='project',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='project_annotations',
                to='project.publishedproject'
            ),
        ),
    ]
