# Generated by Django 4.2.22 on 2025-09-16 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0085_activeproject_georestricted_and_more'),
        ('annotation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotationcollection',
            name='slug',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='annotation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='annotation_type_slug', to='annotation.annotationtype'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_slug', to='annotation.annotationcollection'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_slug', to='project.publishedproject'),
        ),
        migrations.AlterField(
            model_name='annotationtype',
            name='slug',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
