# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-30 18:17
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AnnotationClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=50, unique=True)),
                ('human_reviewed', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='AnnotationLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='ClinicalType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Database',
            fields=[
                ('projectdatabase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.ProjectDatabase')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('publishdate', models.DateField(blank=True)),
                ('overview', models.TextField(max_length=1500)),
                ('acknowledgements', models.TextField(blank=True)),
                ('DOI', models.CharField(max_length=100, unique=True)),
                ('version', models.CharField(max_length=50)),
                ('isopen', models.BooleanField(default=True)),
                ('DUA', ckeditor.fields.RichTextField(blank=True, default='')),
                ('visits', models.IntegerField(default=0)),
                ('downloads', models.IntegerField(default=0)),
                ('changelog', ckeditor.fields.RichTextField(blank=True, default='')),
                ('size', models.IntegerField()),
                ('associated_pages', models.ManyToManyField(blank=True, related_name='physiobank_database', to='catalog.Link')),
            ],
            options={
                'abstract': False,
            },
            bases=('catalog.projectdatabase', models.Model),
        ),
        migrations.CreateModel(
            name='DataType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('basefs', models.FloatField(blank=True)),
                ('sig_duration', models.IntegerField(blank=True)),
                ('gender', models.BinaryField(blank=True, null=True)),
                ('age', models.SmallIntegerField(blank=True, null=True)),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record', to='physiobank.Database')),
            ],
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('fs', models.FloatField()),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='physiobank.Record')),
            ],
        ),
        migrations.CreateModel(
            name='SignalClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='signal',
            name='sig_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signal', to='physiobank.SignalClass'),
        ),
    ]
