# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-30 18:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('physiobank', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0002_auto_20170830_1817'),
        ('physionetworks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='authorizers',
            field=models.ManyToManyField(blank=True, related_name='physiobank_database_authorizer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='database',
            name='clinicaltypes',
            field=models.ManyToManyField(blank=True, default=None, related_name='database', to='physiobank.ClinicalType'),
        ),
        migrations.AddField(
            model_name='database',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='physiobank_database', to='catalog.Contact'),
        ),
        migrations.AddField(
            model_name='database',
            name='contributors',
            field=models.ManyToManyField(blank=True, related_name='physiobank_database', to='catalog.Contributor'),
        ),
        migrations.AddField(
            model_name='database',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='physiobank_database', to='catalog.File'),
        ),
        migrations.AddField(
            model_name='database',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='physiobank_database', to='catalog.Keyword'),
        ),
        migrations.AddField(
            model_name='database',
            name='license',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='physiobank_database', to='catalog.License'),
        ),
        migrations.AddField(
            model_name='database',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='physiobank_database_member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='database',
            name='originproject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='physiobank_database', to='physionetworks.Project'),
        ),
        migrations.AddField(
            model_name='database',
            name='signalclasses',
            field=models.ManyToManyField(blank=True, default=None, related_name='database', to='physiobank.SignalClass'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='ann_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotation', to='physiobank.AnnotationClass'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='labels',
            field=models.ManyToManyField(related_name='annotation', to='physiobank.AnnotationLabel'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='physiobank.Record'),
        ),
    ]
