# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-30 18:17
from __future__ import unicode_literals

import catalog.models
import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('institution', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('institution', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DUA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('directory', models.CharField(max_length=200)),
                ('file', models.FileField(blank=True, default='', null=True, upload_to=catalog.models.user_directory_path)),
                ('size', models.BigIntegerField(blank=True, default=0, null=True)),
                ('lastmtime', models.DateField()),
                ('extension', models.CharField(blank=True, default='', max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection', ckeditor.fields.RichTextField(blank=True, default='', null=True)),
                ('filedescription', ckeditor.fields.RichTextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectToolkit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installation', ckeditor.fields.RichTextField()),
                ('usage', ckeditor.fields.RichTextField(blank=True, default='', null=True)),
                ('testedplatforms', ckeditor.fields.RichTextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('url', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
