# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-30 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('physiotoolkit', '0001_initial'),
        ('physiobank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttoolkit',
            name='languages',
            field=models.ManyToManyField(related_name='catalog_projecttoolkit', to='physiotoolkit.Language'),
        ),
        migrations.AddField(
            model_name='projectdatabase',
            name='datatypes',
            field=models.ManyToManyField(related_name='catalog_projectdatabase', to='physiobank.DataType'),
        ),
    ]
