# Generated by Django 2.1.7 on 2019-03-04 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userlogin'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyCredential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_names', models.CharField(blank=True, default='', max_length=100)),
                ('last_name', models.CharField(blank=True, default='', max_length=100)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('mimic_approval_date', models.CharField(max_length=100)),
                ('eicu_approval_date', models.CharField(blank=True, default='', max_length=100)),
                ('info', models.CharField(blank=True, default='', max_length=300)),
                ('migrated', models.BooleanField(default=False)),
                ('migration_date', models.DateTimeField(null=True)),
            ],
        ),
    ]
