# Generated by Django 2.1.7 on 2019-03-04 22:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_legacycredential'),
    ]

    operations = [
        migrations.AddField(
            model_name='legacycredential',
            name='migrated_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
