# Generated by Django 2.1.7 on 2019-03-14 17:22

from django.db import migrations, models
import user.validators


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_legacycredential_migrated_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credentialapplication',
            old_name='website',
            new_name='webpage',
        ),
        migrations.RemoveField(
            model_name='credentialapplication',
            name='course_name',
        ),
        migrations.RemoveField(
            model_name='credentialapplication',
            name='course_number',
        ),
        migrations.AddField(
            model_name='credentialapplication',
            name='course_info',
            field=models.CharField(default='', max_length=100, validators=[user.validators.validate_alphaplusplus]),
        ),
        migrations.AddField(
            model_name='credentialapplication',
            name='research_summary',
            field=models.CharField(default='', max_length=1000, validators=[user.validators.validate_alphaplusplus]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='credentialapplication',
            name='course_category',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Not for a course'), (1, 'I am taking a course using the data')]),
        ),
        migrations.AlterField(
            model_name='credentialapplication',
            name='reference_category',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Supervisor (required for students and Postdocs)'), (1, 'Colleague'), (2, 'Coauthor'), (3, 'Other')]),
        ),
    ]
