# Generated by Django 2.1.7 on 2019-05-08 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_credentialapplication_reference_response_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pgp_key_id',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
