# Generated by Django 2.1.7 on 2019-05-10 16:20

from django.db import migrations, models
import user.validators


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_credentialapplication_reference_response_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentialapplication',
            name='suffix',
            field=models.CharField(blank=True, default='', max_length=60, validators=[user.validators.validate_alphaplusplus]),
        ),
        migrations.AddField(
            model_name='credentialapplication',
            name='zip_code',
            field=models.CharField(blank=True, default='', max_length=60, validators=[user.validators.validate_alphaplusplus]),
        ),
    ]
