# Generated by Django 2.1.7 on 2019-05-08 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_profile_phone_number'),
        ('user', '0008_profile_pgp_key_id'),
    ]

    operations = [
    ]
