# Generated by Django 2.1.7 on 2019-05-16 13:56

from django.db import migrations, models
import user.validators


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20190514_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentialapplication',
            name='reference_response_text',
            field=models.CharField(max_length=2000, validators=[user.validators.validate_alphaplusplus]),
        ),
    ]
