# Generated by Django 2.1.7 on 2019-05-16 15:58

from django.db import migrations, models
import user.validators


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20190516_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentialapplication',
            name='suffix',
            field=models.CharField(blank=True, default='', max_length=60, validators=[user.validators.validate_nan, user.validators.validate_alphaplusplus]),
        ),
    ]
