# Generated by Django 2.1.9 on 2019-06-18 12:32

from django.db import migrations, models
import user.validators


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20190516_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentialapplication',
            name='zip_code',
            field=models.CharField(max_length=60, validators=[user.validators.validate_alphaplusplus]),
        ),
    ]
