# Generated by Django 2.1.9 on 2019-06-19 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0022_author_creation_date'),
        ('user', '0013_auto_20190618_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentialapplication',
            name='project_of_interest',
            field=models.ForeignKey(limit_choices_to={'access_policy': 2}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.PublishedProject'),
        ),
    ]
