# Generated by Django 2.1.7 on 2019-07-09 14:05

from django.db import migrations, models
import user.validators


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_credentialapplication_project_of_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='affiliation',
            field=models.CharField(blank=True, default='', max_length=250, validators=[user.validators.validate_alphaplusplus]),
        ),
    ]
