# Generated by Django 2.1.9 on 2019-08-12 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_auto_20190725_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='legacycredential',
            name='reference_email',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
