# Generated by Django 2.2.4 on 2019-08-27 18:54

from django.db import migrations, models
import user.validators


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_legacycredential_reference_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentialapplication',
            name='course_category',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Not for a course'), (1, 'I am taking a course using the data')], null=True),
        ),
        migrations.AlterField(
            model_name='credentialapplication',
            name='course_info',
            field=models.CharField(blank=True, default='', max_length=100, validators=[user.validators.validate_alphaplusplus]),
        ),
        migrations.AlterField(
            model_name='credentialapplication',
            name='training_completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='credentialapplication',
            name='training_course_name',
            field=models.CharField(blank=True, default='', max_length=100, validators=[user.validators.validate_alphaplusplus]),
        ),
    ]
