# Generated by Django 2.2.4 on 2019-08-26 20:48

from django.db import migrations, models
import user.validators


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_legacycredential_reference_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentialapplication',
            name='reference_category',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Supervisor (required for students and Postdocs)'), (1, 'Colleague'), (2, 'Coauthor'), (3, 'Other')], null=True),
        ),
        migrations.AlterField(
            model_name='credentialapplication',
            name='reference_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='credentialapplication',
            name='reference_name',
            field=models.CharField(blank=True, default='', max_length=202, validators=[user.validators.validate_name]),
        ),
        migrations.AlterField(
            model_name='credentialapplication',
            name='reference_title',
            field=models.CharField(blank=True, default='', max_length=60, validators=[user.validators.validate_alphaplusplus]),
        ),
    ]
