# Generated by Django 2.2.4 on 2019-08-27 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_auto_20190827_1454'),
        ('user', '0019_auto_20190826_1648'),
    ]

    operations = [
    ]
