# Generated by Django 2.2.4 on 2019-09-16 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_merge_20190827_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentialapplication',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[('', '-----------'), (1, 'Reject'), (2, 'Accept'), (3, 'Withdrawn')], default=0),
        ),
    ]
