# Generated by Django 2.2.4 on 2019-10-08 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_auto_20190927_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentialapplication',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[('', '-----------'), (1, 'Reject'), (2, 'Accept'), (3, 'Withdrawn')], default=0),
        ),
    ]
