# Generated by Django 2.2.6 on 2019-11-25 20:00

from django.db import migrations, models
import user.validators


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_auto_20191008_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentialapplication',
            name='city',
            field=models.CharField(max_length=100, validators=[user.validators.validate_city]),
        ),
        migrations.AlterField(
            model_name='credentialapplication',
            name='course_info',
            field=models.CharField(blank=True, default='', max_length=100, validators=[user.validators.validate_course]),
        ),
        migrations.AlterField(
            model_name='credentialapplication',
            name='job_title',
            field=models.CharField(max_length=60, validators=[user.validators.validate_job_title]),
        ),
        migrations.AlterField(
            model_name='credentialapplication',
            name='organization_name',
            field=models.CharField(max_length=60, validators=[user.validators.validate_organization]),
        ),
        migrations.AlterField(
            model_name='credentialapplication',
            name='reference_name',
            field=models.CharField(blank=True, default='', max_length=202, validators=[user.validators.validate_reference_name]),
        ),
        migrations.AlterField(
            model_name='credentialapplication',
            name='reference_response_text',
            field=models.CharField(max_length=2000, validators=[user.validators.validate_reference_response]),
        ),
        migrations.AlterField(
            model_name='credentialapplication',
            name='reference_title',
            field=models.CharField(blank=True, default='', max_length=60, validators=[user.validators.validate_reference_title]),
        ),
        migrations.AlterField(
            model_name='credentialapplication',
            name='research_summary',
            field=models.CharField(max_length=1000, validators=[user.validators.validate_research_summary]),
        ),
        migrations.AlterField(
            model_name='credentialapplication',
            name='state_province',
            field=models.CharField(blank=True, default='', max_length=100, validators=[user.validators.validate_state]),
        ),
        migrations.AlterField(
            model_name='credentialapplication',
            name='suffix',
            field=models.CharField(blank=True, default='', max_length=60, validators=[user.validators.validate_suffix]),
        ),
        migrations.AlterField(
            model_name='credentialapplication',
            name='training_course_name',
            field=models.CharField(blank=True, default='', max_length=100, validators=[user.validators.validate_training_course]),
        ),
        migrations.AlterField(
            model_name='credentialapplication',
            name='zip_code',
            field=models.CharField(max_length=60, validators=[user.validators.validate_zipcode]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='affiliation',
            field=models.CharField(blank=True, default='', max_length=250, validators=[user.validators.validate_affiliation]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, default='', max_length=100, validators=[user.validators.validate_location]),
        ),
    ]
