# Generated by Django 2.2.10 on 2020-03-06 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_auto_20191125_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='associatedemail',
            name='verification_token',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
