# Generated by Django 2.2.10 on 2020-04-02 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_associatedemail_verification_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legacycredential',
            name='migrated_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legacy_application', to=settings.AUTH_USER_MODEL),
        ),
    ]
