# Generated by Django 2.2.10 on 2020-04-09 15:12

from django.db import migrations, models
import user.validators


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_associatedemail_verification_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentialapplication',
            name='organization_name',
            field=models.CharField(max_length=200, validators=[user.validators.validate_organization]),
        ),
    ]
