# Generated by Django 2.2.10 on 2020-04-10 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user.validators


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_associatedemail_verification_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentialapplication',
            name='organization_name',
            field=models.CharField(max_length=200, validators=[user.validators.validate_organization]),
        ),
        migrations.AlterField(
            model_name='legacycredential',
            name='migrated_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legacy_application', to=settings.AUTH_USER_MODEL),
        ),
    ]
