# Generated by Django 2.2.10 on 2020-08-05 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_auto_20200805_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentialapplication',
            name='revoked_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='legacycredential',
            name='revoked_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
