# Generated by Django 2.2.13 on 2020-10-14 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_auto_20200805_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentialapplication',
            name='researcher_category',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Student'), (7, 'Graduate Student'), (1, 'Postdoc'), (2, 'Academic Researcher'), (3, 'Hospital Researcher'), (4, 'Industry Researcher'), (5, 'Government Researcher'), (6, 'Independent Researcher')]),
        ),
    ]
