# Generated by Django 2.2.10 on 2020-04-17 20:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0028_auto_20201014_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentialapplication',
            name='training_completion_report_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
