# Generated by Django 2.2.13 on 2021-01-22 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_credentialapplication_url_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='CredentialReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[('', '-----------'), (0, 'Not in review'), (10, 'Initial review'), (20, 'Training'), (30, 'ID check'), (40, 'Reference'), (50, 'Reference response'), (60, 'Final review')], default=10)),
                ('fields_complete', models.BooleanField(null=True)),
                ('appears_correct', models.BooleanField(null=True)),
                ('lang_understandable', models.BooleanField(null=True)),
                ('citi_report_attached', models.BooleanField(null=True)),
                ('training_current', models.BooleanField(null=True)),
                ('training_all_modules', models.BooleanField(null=True)),
                ('training_privacy_complete', models.BooleanField(null=True)),
                ('training_name_match', models.BooleanField(null=True)),
                ('user_searchable', models.BooleanField(null=True)),
                ('user_has_papers', models.BooleanField(null=True)),
                ('research_summary_clear', models.BooleanField(null=True)),
                ('course_name_provided', models.BooleanField(null=True)),
                ('user_understands_privacy', models.BooleanField(null=True)),
                ('user_org_known', models.BooleanField(null=True)),
                ('user_details_consistent', models.BooleanField(null=True)),
                ('ref_appropriate', models.BooleanField(null=True)),
                ('ref_searchable', models.BooleanField(null=True)),
                ('ref_has_papers', models.BooleanField(null=True)),
                ('ref_is_supervisor', models.BooleanField(null=True)),
                ('ref_course_list', models.BooleanField(null=True)),
                ('ref_skipped', models.BooleanField(null=True)),
                ('ref_knows_applicant', models.BooleanField(null=True)),
                ('ref_approves', models.BooleanField(null=True)),
                ('ref_understands_privacy', models.BooleanField(null=True)),
                ('responder_comments', models.CharField(blank=True, default='', max_length=500)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credential_review', to='user.CredentialApplication')),
            ],
        ),
    ]
