# Generated by Django 2.2.13 on 2021-01-27 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_credentialreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentialapplication',
            name='internal_comments',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='credentialreview',
            name='internal_comments',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
