# Generated by Django 2.2.13 on 2021-01-23 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_credentialreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentialapplication',
            name='app_contact_comments',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
    ]
