# Generated by Django 2.2.13 on 2021-01-20 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_credentialapplication_submission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentialapplication',
            name='organization_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
