# Generated by Django 2.2.13 on 2021-04-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_orcid'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorite_color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
