# Generated by Django 2.2.13 on 2021-03-12 18:40

from django.db import migrations, models
import user.validators


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0033_credentialapplication_reference_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_name', models.CharField(blank=True, default='', max_length=202, validators=[user.validators.validate_reference_name])),
                ('reference_email', models.EmailField(blank=True, default='', max_length=254)),
                ('reference_organization', models.CharField(blank=True, max_length=200, validators=[user.validators.validate_organization])),
                ('class_name', models.CharField(blank=True, max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('creation_datetime', models.DateTimeField(null=True)),
                ('deactivate_date_time', models.DateTimeField(null=True)),
            ],
        ),
    ]
