# Generated by Django 2.2.24 on 2021-11-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0033_credentialapplication_reference_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sso_id',
            field=models.CharField(max_length=256, null=True, unique=True),
        ),
    ]
