# Generated by Django 2.2.24 on 2021-12-15 13:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import user.enums
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0033_credentialapplication_reference_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'REVIEW'), (1, 'WITHDRAWN'), (2, 'REJECTED'), (3, 'ACCEPTED')], default=user.enums.TrainingStatus(0))),
                ('completion_report', models.FileField(blank=True, upload_to=user.models.get_training_path, validators=[django.core.validators.FileExtensionValidator(['pdf'], 'File must be a pdf.')])),
                ('completion_report_url', models.URLField(blank=True)),
                ('application_datetime', models.DateTimeField(auto_now_add=True)),
                ('process_datetime', models.DateTimeField(null=True)),
                ('reviewer_comments', models.CharField(max_length=512)),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_trainings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='credentialapplication',
            name='training_completion_date',
        ),
        migrations.RemoveField(
            model_name='credentialapplication',
            name='training_completion_report',
        ),
        migrations.RemoveField(
            model_name='credentialapplication',
            name='training_completion_report_url',
        ),
        migrations.RemoveField(
            model_name='credentialapplication',
            name='training_course_name',
        ),
        migrations.RemoveField(
            model_name='credentialreview',
            name='citi_report_attached',
        ),
        migrations.RemoveField(
            model_name='credentialreview',
            name='training_all_modules',
        ),
        migrations.RemoveField(
            model_name='credentialreview',
            name='training_current',
        ),
        migrations.RemoveField(
            model_name='credentialreview',
            name='training_name_match',
        ),
        migrations.RemoveField(
            model_name='credentialreview',
            name='training_privacy_complete',
        ),
        migrations.AlterField(
            model_name='credentialreview',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[('', '-----------'), (0, 'Not in review'), (10, 'Initial review'), (20, 'ID check'), (30, 'Reference'), (40, 'Reference response'), (50, 'Final review')], default=10),
        ),
        migrations.CreateModel(
            name='TrainingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(max_length=1024)),
                ('valid_duration', models.DurationField(null=True)),
                ('required_field', models.PositiveSmallIntegerField(choices=[(0, 'DOCUMENT'), (1, 'URL')], default=user.enums.RequiredField(0))),
                ('questions', models.ManyToManyField(related_name='training_types', to='user.Question')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.NullBooleanField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Question')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_questions', to='user.Training')),
            ],
        ),
        migrations.AddField(
            model_name='training',
            name='training_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.TrainingType'),
        ),
        migrations.AddField(
            model_name='training',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to=settings.AUTH_USER_MODEL),
        ),
    ]
