# Generated by Django 2.2.24 on 2021-12-15 13:59
from django.conf import settings

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.db.models.fields import DurationField

from project.modelcomponents.fields import SafeHTMLField
from user.enums import TrainingStatus, RequiredField
from user.models import get_training_path
from user.validators import validate_alphaplusplus


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0034_user_sso_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=20, unique=True)),
                (
                    'status',
                    models.PositiveSmallIntegerField(
                        choices=[(0, 'REVIEW'), (1, 'WITHDRAWN'), (2, 'REJECTED'), (3, 'ACCEPTED')],
                        default=TrainingStatus(0),
                    ),
                ),
                (
                    'completion_report',
                    models.FileField(
                        blank=True,
                        upload_to=get_training_path,
                        validators=[django.core.validators.FileExtensionValidator(['pdf'], 'File must be a pdf.')],
                    ),
                ),
                ('completion_report_url', models.URLField(blank=True)),
                ('application_datetime', models.DateTimeField(auto_now_add=True)),
                ('process_datetime', models.DateTimeField(null=True)),
                ('reviewer_comments', models.CharField(max_length=512)),
                (
                    'reviewer',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='reviewed_training',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='TrainingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('home_page', models.URLField(blank=True)),
                ('description', SafeHTMLField()),
                ('valid_duration', DurationField(null=True)),
                (
                    'required_field',
                    models.PositiveSmallIntegerField(
                        choices=[(0, 'DOCUMENT'), (1, 'URL')], default=RequiredField(0)
                    ),
                ),
                ('questions', models.ManyToManyField(related_name='training_types', to='user.Question')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.NullBooleanField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Question')),
                (
                    'training',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='training_questions',
                        to='user.Training',
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='training',
            name='training_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.TrainingType'),
        ),
        migrations.AddField(
            model_name='training',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='training', to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name='credentialapplication',
            name='training_completion_report',
            field=models.FileField(
                upload_to=get_training_path,
                null=True,
                validators=[django.core.validators.FileExtensionValidator(['pdf'], 'File must be a pdf.')]
            )
        ),
        migrations.AlterField(
            model_name='credentialapplication',
            name='training_course_name',
            field=models.CharField(
                max_length=100,
                null=True,
                validators=[validate_alphaplusplus]
            )
        )
    ]
