# Generated by Django 2.2.27 on 2022-03-22 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0036_training_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingRegex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=48)),
                ('regex', models.CharField(max_length=128)),
                ('training_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                    related_name='certificate_regexes',
                                                    to='user.TrainingType')),
            ],
        ),
    ]
