# Generated by Django 2.2.27 on 2022-03-24 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0037_auto_20220322_0717'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingRegex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=48)),
                ('regex', models.CharField(max_length=128)),
                ('display_order', models.PositiveSmallIntegerField()),
                ('training_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                    related_name='certificate_regexes',
                                                    to='user.TrainingType')),
            ],
            options={
                'unique_together': {('display_order', 'training_type')},
            },
        ),
    ]
