# Generated by Django 2.2.26 on 2022-02-07 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import project.modelcomponents.fields
import project.validators


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0038_trainingregex'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeOfConduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                (
                    'version',
                    models.CharField(
                        default='',
                        max_length=15,
                        validators=[project.validators.validate_version],
                    ),
                ),
                ('is_active', models.BooleanField(default=False)),
                ('html_content', project.modelcomponents.fields.SafeHTMLField(default='')),
            ],
            options={
                'unique_together': {('name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='CodeOfConductSignature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_datetime', models.DateTimeField(auto_now_add=True)),
                (
                    'code_of_conduct',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='user.CodeOfConduct',
                    ),
                ),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
