# Generated by Django 2.2.27 on 2022-03-30 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0041_permissions_2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codeofconduct',
            options={'default_permissions': ('add',)},
        ),
        migrations.AlterModelOptions(
            name='codeofconductsignature',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='training',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='trainingquestion',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='trainingregex',
            options={'default_permissions': ()},
        ),
        migrations.AlterModelOptions(
            name='trainingtype',
            options={'default_permissions': ()},
        ),
    ]
