# Generated by Django 2.2.28 on 2022-07-20 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user.enums


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0045_auto_20220528_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('event_type', models.PositiveSmallIntegerField(choices=[(0, 'COURSE'),
                                                                         (1, 'DATATHON'),
                                                                         (2, 'CONFERENCE'),
                                                                         (3, 'WORKSHOP'),
                                                                         (4, 'SYMPOSIUM')],
                                                                default=user.enums.EventType(0))),
                ('added_datetime', models.DateTimeField(auto_now_add=True)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('name', 'host')},
            },
        ),
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Event')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                  to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('participant', 'course')},
            },
        ),
    ]
