# Generated by Django 3.1.14 on 2022-11-25 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0047_event_allowed_domains'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'default_permissions': ('view',), 'permissions': [('can_view_admin_console', 'Can view the Admin Console')]},
        ),
    ]
