# Generated by Django 3.1.14 on 2022-12-16 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0048_auto_20221129_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='associated_emails_allowed',
            field=models.IntegerField(default=10),
        ),
    ]
