# Generated by Django 3.1.14 on 2023-01-10 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0048_auto_20221129_1512'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingtype',
            options={'default_permissions': (), 'permissions': [('can_review_training', 'Can Review Training')]},
        ),
    ]
