# Generated by Django 3.1.14 on 2023-01-03 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0048_auto_20221129_1512'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingtype',
            options={'default_permissions': (), 'permissions': [('can_review_training', 'Can Review Training')]},
        ),
        migrations.AddField(
            model_name='trainingtype',
            name='short_term_training',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
