# Generated by Django 3.1.14 on 2022-12-16 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0049_user_associated_emails_allowed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='associated_emails_allowed',
            field=models.IntegerField(default=10, null=True),
        ),
    ]
