# Generated by Django 3.2.16 on 2023-01-19 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0049_auto_20230112_1430'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingtype',
            options={'default_permissions': (), 'permissions': [('can_review_training', 'Can Review Training')]},
        ),
    ]
