# Generated by Django 3.2.16 on 2023-02-09 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0050_alter_trainingtype_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentialapplication',
            name='auto_rejection_reason',
            field=models.CharField(blank=True, choices=[('NRFR', 'No response from reference')], max_length=4,
                                   null=True),
        ),
    ]
