# Generated by Django 3.1.14 on 2022-12-16 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0050_auto_20221216_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='associated_emails_allowed',
        ),
    ]
