# Generated by Django 4.1.5 on 2023-02-14 08:00

from django.db import migrations, models
import user.enums


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0051_credentialapplication_auto_rejection_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingtype',
            name='required_field',
            field=models.PositiveSmallIntegerField(
                choices=[(0, 'DOCUMENT'), (1, 'URL'), (2, 'PLATFORM')],
                default=user.enums.RequiredField['DOCUMENT']),
        ),
    ]
