# Generated by Django 3.2.16 on 2023-03-01 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0051_credentialapplication_auto_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentialapplication',
            name='reference_reminder_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
