# Generated by Django 3.2.16 on 2023-03-14 22:03

from django.db import migrations, models
from django.utils.crypto import get_random_string


def migrate_forward(apps, schema_editor):
    CredentialApplication = apps.get_model('user', 'CredentialApplication')
    applications = CredentialApplication.objects.filter(
        reference_verification_token__isnull=True,
        reference_response_datetime=None,
        status=0)
    for application in applications:
        application.reference_verification_token = get_random_string(length=32)
        application.save()


def migrate_backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0052_credentialapplication_reminder_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentialapplication',
            name='reference_verification_token',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.RunPython(migrate_forward, migrate_backward),
    ]
