# Generated by Django 3.1.14 on 2023-03-30 21:23

from django.db import migrations, models
import user.validators


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0054_alter_credentialapplication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentialapplication',
            name='reference_category',
            field=models.PositiveSmallIntegerField(
                choices=[(0, 'Supervisor (required for students and Postdocs)'),
                         (1, 'Colleague'), (2, 'Coauthor'), (3, 'Other')], null=True),
        ),
        migrations.AlterField(
            model_name='credentialapplication',
            name='reference_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='credentialapplication',
            name='reference_name',
            field=models.CharField(default='', max_length=202,
                                   validators=[user.validators.validate_reference_name]),
        ),
        migrations.AlterField(
            model_name='credentialapplication',
            name='reference_organization',
            field=models.CharField(max_length=200,
                                   validators=[user.validators.validate_organization]),
        ),
        migrations.AlterField(
            model_name='credentialapplication',
            name='reference_title',
            field=models.CharField(default='', max_length=60,
                                   validators=[user.validators.validate_reference_title]),
        ),
    ]
