# Generated by Django 4.1.10 on 2023-08-28 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0056_alter_trainingtype_required_field'),
        ('user', '0056_remove_credentialreview_appears_correct_and_more'),
    ]

    operations = [
    ]
