# Generated by Django 4.1.10 on 2023-10-04 21:14

from django.db import migrations, models
import user.validators


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0056_remove_credentialreview_appears_correct_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cloudinformation",
            name="aws_id",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=60,
                null=True,
                validators=[user.validators.validate_aws_id],
            ),
        ),
    ]
