# Generated by Django 4.1.13 on 2023-12-13 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0071_alter_activeproject_options_and_more'),
        ('user', '0057_alter_cloudinformation_aws_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TrainingType',
            new_name='Course',
        ),
    ]
