# Generated by Django 4.1.13 on 2023-11-27 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0057_alter_cloudinformation_aws_id'),
        ('user', '0057_merge_20230828_1158'),
    ]

    operations = [
    ]
