# Generated by Django 4.1.10 on 2023-10-27 22:00

from django.db import migrations, models
import user.validators


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0057_alter_cloudinformation_aws_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="cloudinformation",
            name="aws_userid",
            field=models.CharField(
                blank=True,
                max_length=30,
                null=True,
                unique=True,
                validators=[user.validators.validate_aws_userid],
            ),
        ),
        migrations.AddField(
            model_name="cloudinformation",
            name="aws_user_arn",
            field=models.CharField(
                blank=True,
                max_length=2048,
                null=True,
                unique=True,
                validators=[user.validators.validate_aws_user_arn],
            ),
        ),
        migrations.AddField(
            model_name="cloudinformation",
            name="aws_verification_datetime",
            field=models.DateTimeField(null=True),
        ),
    ]
