# Generated by Django 4.1.13 on 2023-12-13 20:17

from django.db import migrations, models
import project.validators


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0058_rename_trainingtype_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='course',
            name='version',
            field=models.CharField(default='', max_length=15, validators=[project.validators.validate_version]),
        ),
    ]
