# Generated by Django 4.1.13 on 2024-03-04 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0058_merge_20231127_1642"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingtype",
            name="slug",
            field=models.SlugField(max_length=128, null=True, unique=True),
        ),
    ]
