# Generated by Django 4.1.13 on 2024-03-04 18:15

from django.db import migrations
from django.utils.text import slugify


def generate_slugs(apps, schema_editor):
    TrainingType = apps.get_model("user", "TrainingType")
    for training_type in TrainingType.objects.all():
        if not training_type.slug:
            slug_base = '{}-{}'.format(training_type.name, training_type.id)
            training_type.slug = slugify(slug_base)
            training_type.save()


def migrate_backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0059_trainingtype_slug"),
    ]

    operations = [
        migrations.RunPython(generate_slugs, migrate_backward),
    ]
