# Generated by Django 4.1.13 on 2024-03-04 18:15

from django.db import migrations
from django.utils.text import slugify


def generate_slugs(apps, schema_editor):
    TrainingType = apps.get_model("user", "TrainingType")
    for training_type in TrainingType.objects.all():
        if not training_type.slug:
            slug = slugify(training_type.name)
            unique_slug = slug
            number = 1
            while TrainingType.objects.filter(slug=unique_slug).exists():
                unique_slug = f"{slug}-{number}"
                number += 1
            training_type.slug = unique_slug
            training_type.save()


def migrate_backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0059_trainingtype_slug"),
    ]

    operations = [
        migrations.RunPython(generate_slugs, migrate_backward),
    ]
