# Generated by Django 4.2.11 on 2024-08-20 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0006_remove_course_trainings_and_more"),
        ("user", "0061_cloudinformation_aws_userid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="training",
            name="course",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="trainings",
                to="training.course",
            ),
        ),
    ]
