# Generated by Django 4.2.14 on 2024-11-15 00:47

from django.db import migrations, models
import user.enums


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0062_training_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="training",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "REVIEW"),
                    (1, "WITHDRAWN"),
                    (2, "REJECTED"),
                    (3, "ACCEPTED"),
                    (4, "IN_PROGRESS"),
                ],
                default=user.enums.TrainingStatus["REVIEW"],
            ),
        ),
    ]
