# Generated by Django 4.2.20 on 2025-12-03 22:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0067_khdpaccount"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="khdpaccount",
            options={"default_permissions": ()},
        ),
    ]
