# Generated by Django 4.2.20 on 2026-01-14 22:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0068_alter_khdpaccount_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="khdpaccount",
            name="orcid",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="khdpaccount",
            name="physionet_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="PhysioNet public user UUID shared with KHDP",
                max_length=128,
            ),
        ),
    ]
