# Generated by Django 4.2 on 2026-01-20
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0069_alter_khdpaccount_orcid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khdpaccount',
            name='khdp_user_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
