# Generated by Django 4.2.20 on 2026-01-20 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0070_alter_khdpaccount_khdp_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="khdpaccount",
            name="access_token",
            field=models.CharField(blank=True, default="", max_length=1024),
        ),
    ]
