# Generated by Django 4.2.30 on 2026-09-09 15:35

from django.db import migrations, models
import django.db.models.deletion


def create_citi_group_mapping(apps, schema_editor):
    TrainingType = apps.get_model('user', 'TrainingType')
    CITIGroupMapping = apps.get_model('user', 'CITIGroupMapping')

    try:
        citi_type = TrainingType.objects.get(name='CITI Data or Specimens Only Research')
        CITIGroupMapping.objects.get_or_create(
            citi_group_id=43007,
            defaults={
                'training_type': citi_type,
                'citi_group_name': 'Data or Specimens Only Research',
            }
        )
    except TrainingType.DoesNotExist:
        pass


def revert_citi_group_mapping(apps, schema_editor):
    CITIGroupMapping = apps.get_model('user', 'CITIGroupMapping')
    CITIGroupMapping.objects.filter(citi_group_id=43007).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0071_alter_khdpaccount_access_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='CITIVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookup_email', models.EmailField(blank=True, default='', max_length=254)),
                ('member_id', models.CharField(blank=True, default='', max_length=32)),
                ('completion_report_id', models.CharField(blank=True, default='', max_length=32)),
                ('member_profile_xml', models.TextField(blank=True, default='')),
                ('completions_xml', models.TextField(blank=True, default='')),
                ('api_error', models.CharField(blank=True, default='', max_length=512)),
                (
                    'training',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='citi_verification',
                        to='user.training',
                    ),
                ),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='CITIGroupMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citi_group_id', models.IntegerField(unique=True)),
                ('citi_group_name', models.CharField(blank=True, max_length=256)),
                (
                    'training_type',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='citi_group_mappings',
                        to='user.trainingtype',
                    ),
                ),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.RunPython(
            create_citi_group_mapping, revert_citi_group_mapping
        ),
    ]
