# Generated by Django 4.2.30 on 2026-09-29 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0072_citi_api_verification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orcid",
            name="name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="orcid",
            name="token_scope",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
    ]
