# Generated by Django 4.2.30 on 2026-09-16 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0072_citi_api_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='newsletter',
            field=models.BooleanField(
                default=False,
                null=True,
                help_text='Whether the user has opted in to receive the newsletter.',
            ),
        ),
        migrations.AddField(
            model_name='profile',
            name='review_volunteer',
            field=models.BooleanField(
                default=False,
                null=True,
                help_text='Whether the user has volunteered to review data submissions.',
            ),
        ),
    ]
