# Generated by Django 5.2.16 on 2026-10-08 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0073_alter_orcid_name_alter_orcid_token_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_activation_email_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
