# Generated by Django 4.2.30 on 2026-09-16 18:48

from django.db import migrations, models


def backfill_defaults(apps, schema_editor):
    Profile = apps.get_model('user', 'Profile')
    Profile.objects.filter(newsletter=None).update(newsletter=False)
    Profile.objects.filter(review_volunteer=None).update(review_volunteer=False)


class Migration(migrations.Migration):

    MIGRATE_AFTER_INSTALL = True

    dependencies = [
        ('user', '0073_profile_newsletter_and_review_volunteer'),
    ]

    operations = [
        migrations.RunPython(backfill_defaults, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='profile',
            name='newsletter',
            field=models.BooleanField(
                default=False,
                help_text='Whether the user has opted in to receive the newsletter.',
            ),
        ),
        migrations.AlterField(
            model_name='profile',
            name='review_volunteer',
            field=models.BooleanField(
                default=False,
                help_text='Whether the user has volunteered to review data submissions.',
            ),
        ),
    ]
