# Generated by Django 4.2.30 on 2026-05-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='requires_pkce',
            field=models.BooleanField(default=True),
        ),
    ]
