# Generated by Django 4.2.30 on 2026-09-27 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challengeconfiguration',
            name='additional_metrics',
            field=models.JSONField(blank=True, default=list, help_text='Secondary scoring metrics. List of JSON objects, each with name, display_name, and sort fields.'),
        ),
        migrations.AlterField(
            model_name='challengeconfiguration',
            name='primary_metric',
            field=models.JSONField(blank=True, default=dict, help_text='Primary metric for ranking. JSON object with name, display_name, and sort fields.'),
        ),
        migrations.AlterField(
            model_name='submissionspec',
            name='additional_metrics',
            field=models.JSONField(blank=True, default=list, help_text='Secondary scoring metrics. List of JSON objects, each with name, display_name, and sort fields.'),
        ),
        migrations.AlterField(
            model_name='submissionspec',
            name='primary_metric',
            field=models.JSONField(blank=True, default=dict, help_text='Primary metric for ranking. JSON object with name, display_name, and sort fields.'),
        ),
    ]
