# Generated by Django 4.2.30 on 2026-09-22 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0101_publishedproject_single_latest_version_per_core_project_and_more'),
        ('challenge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_open_datetime', models.DateTimeField(blank=True, null=True)),
                ('start_datetime', models.DateTimeField(blank=True, null=True)),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('max_submissions_per_day', models.PositiveIntegerField(default=5)),
                ('max_total_submissions', models.PositiveIntegerField(default=100)),
                ('teams_enabled', models.BooleanField(default=False)),
                ('base_image', models.CharField(default='python:3.11-slim', max_length=200)),
                ('entrypoint_command', models.CharField(default='python main.py', max_length=500)),
                ('max_runtime_seconds', models.PositiveIntegerField(default=3600)),
                ('max_memory_mb', models.PositiveIntegerField(default=4096)),
                ('gpu_enabled', models.BooleanField(default=False)),
                ('gpu_type', models.CharField(blank=True, default='', max_length=50)),
                ('cpu_count', models.PositiveIntegerField(default=2)),
                ('input_format', models.JSONField(blank=True, default=dict)),
                ('output_format', models.JSONField(blank=True, default=dict)),
                ('primary_metric_name', models.CharField(default='score', max_length=100)),
                ('primary_metric_sort', models.CharField(choices=[('asc', 'Ascending (lower is better)'), ('desc', 'Descending (higher is better)')], default='desc', max_length=4)),
                ('additional_metrics', models.JSONField(blank=True, default=list)),
                ('evaluation_script_path', models.CharField(blank=True, default='evaluation/evaluate.py', help_text='Path to the evaluation script within the project files.', max_length=500)),
                ('hidden_test_data_path', models.CharField(blank=True, default='hidden_test_data/', help_text='Path to the hidden test data directory within the project files.', max_length=500)),
                ('active_project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_config', to='project.activeproject')),
            ],
        ),
    ]
