# Generated by Django 4.2.30 on 2026-09-24 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0004_update_phase_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='official_start_datetime',
            field=models.DateTimeField(blank=True, help_text='When the official phase begins.', null=True),
        ),
        migrations.AddField(
            model_name='challengeconfiguration',
            name='official_start_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='start_datetime',
            field=models.DateTimeField(blank=True, help_text='When the unofficial phase opens for submissions.', null=True),
        ),
    ]
