# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-30 18:17
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Toolkit',
            fields=[
                ('projecttoolkit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.ProjectToolkit')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('publishdate', models.DateField(blank=True)),
                ('overview', models.TextField(max_length=1500)),
                ('acknowledgements', models.TextField(blank=True)),
                ('DOI', models.CharField(max_length=100, unique=True)),
                ('version', models.CharField(max_length=50)),
                ('isopen', models.BooleanField(default=True)),
                ('DUA', ckeditor.fields.RichTextField(blank=True, default='')),
                ('visits', models.IntegerField(default=0)),
                ('downloads', models.IntegerField(default=0)),
                ('changelog', ckeditor.fields.RichTextField(blank=True, default='')),
                ('associated_pages', models.ManyToManyField(blank=True, related_name='physiotoolkit_toolkit', to='catalog.Link')),
            ],
            options={
                'abstract': False,
            },
            bases=('catalog.projecttoolkit', models.Model),
        ),
    ]
