# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-30 18:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('physionetworks', '0002_auto_20170830_1817'),
        ('physiotoolkit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0002_auto_20170830_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolkit',
            name='authorizers',
            field=models.ManyToManyField(blank=True, related_name='physiotoolkit_toolkit_authorizer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='toolkit',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='physiotoolkit_toolkit', to='catalog.Contact'),
        ),
        migrations.AddField(
            model_name='toolkit',
            name='contributors',
            field=models.ManyToManyField(blank=True, related_name='physiotoolkit_toolkit', to='catalog.Contributor'),
        ),
        migrations.AddField(
            model_name='toolkit',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='physiotoolkit_toolkit', to='catalog.File'),
        ),
        migrations.AddField(
            model_name='toolkit',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='physiotoolkit_toolkit', to='catalog.Keyword'),
        ),
        migrations.AddField(
            model_name='toolkit',
            name='license',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='physiotoolkit_toolkit', to='catalog.License'),
        ),
        migrations.AddField(
            model_name='toolkit',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='physiotoolkit_toolkit_member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='toolkit',
            name='originproject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='physiotoolkit_toolkit', to='physionetworks.Project'),
        ),
    ]
